{
 "title": "Netex Output",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "environment", "query": "metrics(FDBT/Netex-Output)" }
  ]
 },
 "panels": [
  {
   "title": "Single - Complete",
   "type": "stat",
   "description": "Successful generation of Single NeTEx",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "metricName": "netex-complete-single-${environment}",
     "namespace": "FDBT/Netex-Output",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "PeriodGeoZone - Complete",
   "type": "stat",
   "description": "Successful generation of PeriodGeoZone NeTEx",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "metricName": "netex-complete-periodgeozone-${environment}",
     "namespace": "FDBT/Netex-Output",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Valid",
   "type": "graph",
   "description": "Valid NeTEx generated",
   "gridPos": { "h": 9, "w": 13, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "metricName": "netex-valid-${environment}", "namespace": "FDBT/Netex-Validator", "region": "default", "statistics": [ "Sum" ] }
   ]
  },
  {
   "title": " Return - Complete",
   "type": "stat",
   "description": "Successful generation of Return NeTEx",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "metricName": "netex-complete-return-${environment}",
     "namespace": "FDBT/Netex-Output",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "PeriodMultipleServices - Complete",
   "type": "stat",
   "description": "Successful generation of PeriodMultipleServices NeTEx",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "metricName": "netex-complete-periodmultipleservices-${environment}",
     "namespace": "FDBT/Netex-Output",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Invalid",
   "type": "graph",
   "description": "Invalid NeTEx generated",
   "gridPos": { "h": 9, "w": 13, "x": 10, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "metricName": "netex-invalid-${environment}", "namespace": "FDBT/Netex-Validator", "region": "default", "statistics": [ "Sum" ] }
   ]
  },
  {
   "title": "FlatFare - Complete",
   "type": "stat",
   "description": "Successful generation of FlatFare NeTEx",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "metricName": "netex-complete-flatfare-${environment}",
     "namespace": "FDBT/Netex-Output",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Emails Sent",
   "type": "stat",
   "description": "Emails sent out with NeTEx files attached.",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "metricName": "SES-emails-sent-${environment}", "namespace": "FDBT/Netex-Emailer", "region": "default", "statistics": [ "Sum" ] }
   ]
  }
 ]
}