{
 "title": "Reference Data",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "environment", "query": "metrics(FDBT/Netex-Output)" }
  ]
 },
 "panels": [
  { "title": "Successful Invocations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Successful TXC Uploader",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": {
      "FunctionName": "reference-data-service-uploaders-prod-TxcUploader"
     },
     "metricName": "Invocations",
     "namespace": "AWS/Lambda",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Successful CSV Uploader",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": {
      "FunctionName": "reference-data-service-uploaders-${environment}-CsvUploader"
     },
     "metricName": "Invocations",
     "namespace": "AWS/Lambda",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Successful TXC Unzipper",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": {
      "FunctionName": "reference-data-service-retrievers-prod-TxcUnzipper"
     },
     "metricName": "Invocations",
     "namespace": "AWS/Lambda",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Successful TXC Retriever",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": {
      "FunctionName": "reference-data-service-retrievers-prod-TxcRetriever"
     },
     "metricName": "Invocations",
     "namespace": "AWS/Lambda",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Successful NaPTAN Retriever",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": {
      "FunctionName": "reference-data-service-retrievers-${environment}-NaptanRetriever"
     },
     "metricName": "Invocations",
     "namespace": "AWS/Lambda",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Successful NOC Retriever",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": {
      "FunctionName": "reference-data-service-retrievers-${environment}-NocRetriever"
     },
     "metricName": "Invocations",
     "namespace": "AWS/Lambda",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  { "title": "Invocation Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Errors TXC Uploader",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": {
      "FunctionName": "reference-data-service-uploaders-prod-TxcUploader"
     },
     "metricName": "Errors",
     "namespace": "AWS/Lambda",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Errors CSV Uploader",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": {
      "FunctionName": "reference-data-service-uploaders-${environment}-CsvUploader"
     },
     "metricName": "Errors",
     "namespace": "AWS/Lambda",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Errors TXC Unzipper",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": {
      "FunctionName": "reference-data-service-retrievers-prod-TxcUnzipper"
     },
     "metricName": "Errors",
     "namespace": "AWS/Lambda",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Errors TXC Retriever",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": {
      "FunctionName": "reference-data-service-retrievers-prod-TxcRetriever"
     },
     "metricName": "Errors",
     "namespace": "AWS/Lambda",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Errors NaPTAN Retriever",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": {
      "FunctionName": "reference-data-service-retrievers-${environment}-NaptanRetriever"
     },
     "metricName": "Errors",
     "namespace": "AWS/Lambda",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Errors NOC Retriever",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": {
      "FunctionName": "reference-data-service-retrievers-${environment}-NocRetriever"
     },
     "metricName": "Errors",
     "namespace": "AWS/Lambda",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  { "title": "Throttled Invocations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Throttled TXC Uploader",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": {
      "FunctionName": "reference-data-service-uploaders-prod-TxcUploader"
     },
     "metricName": "Throttles",
     "namespace": "AWS/Lambda",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Throttled CSV Uploader",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": {
      "FunctionName": "reference-data-service-uploaders-${environment}-CsvUploader"
     },
     "metricName": "Throttles",
     "namespace": "AWS/Lambda",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Throttled TXC Unzipper",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": {
      "FunctionName": "reference-data-service-retrievers-prod-TxcUnzipper"
     },
     "metricName": "Throttles",
     "namespace": "AWS/Lambda",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Throttled TXC Retriever",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": {
      "FunctionName": "reference-data-service-retrievers-prod-TxcRetriever"
     },
     "metricName": "Throttles",
     "namespace": "AWS/Lambda",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Throttled NaPTAN Retriever",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": {
      "FunctionName": "reference-data-service-retrievers-${environment}-NaptanRetriever"
     },
     "metricName": "Throttles",
     "namespace": "AWS/Lambda",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Throttled NOC Retriever",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": {
      "FunctionName": "reference-data-service-retrievers-${environment}-NocRetriever"
     },
     "metricName": "Throttles",
     "namespace": "AWS/Lambda",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  }
 ]
}