{
 "title": "Site",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Started Transactions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "metricName": "startedTransactions", "namespace": "FDBT/Site", "region": "default", "statistics": [ "Sum" ] }
   ]
  },
  {
   "title": "Successful transactions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "metricName": "completeTransactions", "namespace": "FDBT/Site", "region": "default", "statistics": [ "Sum" ] }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "metricName": "responseTime", "namespace": "FDBT/Site", "region": "default", "statistics": [ "Average" ] }
   ]
  },
  {
   "title": "Response Codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "metricName": "2xxResponses", "namespace": "FDBT/Site", "region": "default", "statistics": [ "Sum" ] },
    { "metricName": "3xxResponses", "namespace": "FDBT/Site", "region": "default", "statistics": [ "Sum" ] },
    { "metricName": "4xxResponses", "namespace": "FDBT/Site", "region": "default", "statistics": [ "Sum" ] },
    { "metricName": "5xxResponses", "namespace": "FDBT/Site", "region": "default", "statistics": [ "Sum" ] }
   ]
  }
 ]
}