{
 "title": "TXC Retrieval",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "BODS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "# File Level\n\nData relevant to the file as a whole         "
   },
   "targets": [
    { "region": "default", "statistics": [ "Average" ] }
   ]
  },
  {
   "title": "BODS - Files Processed with Data",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": { "By Data Source": "bods" },
     "metricName": "FilesProcessedWithData",
     "namespace": "FDBT/Reference-Data-Uploaders",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "BODS - Files Processed with no Useable Data",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": { "By Data Source": "bods" },
     "metricName": "FilesProcessedNoData",
     "namespace": "FDBT/Reference-Data-Uploaders",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "BODS - Files Processed with no NOCs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": { "By Data Source": "bods" },
     "metricName": "NoNOCsInFile",
     "namespace": "FDBT/Reference-Data-Uploaders",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "BODS - Files Processed with Invalid NOCs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": { "By Data Source": "bods" },
     "metricName": "InvalidNoc",
     "namespace": "FDBT/Reference-Data-Uploaders",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "BODS - Files Processed with No Operator Data",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": { "By Data Source": "bods" },
     "metricName": "NoOperatorData",
     "namespace": "FDBT/Reference-Data-Uploaders",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "BODS - Files Processed with No Service Data",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": { "By Data Source": "bods" },
     "metricName": "NoServiceDataInFile",
     "namespace": "FDBT/Reference-Data-Uploaders",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "BODS - Files Processed with No Line Data",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": { "By Data Source": "bods" },
     "metricName": "NoLineDataInFile",
     "namespace": "FDBT/Reference-Data-Uploaders",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "BODS - Total Files Retrieved",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": { "By Data Source": "bods" },
     "metricName": "TxcFilesCopied",
     "namespace": "FDBT/Reference-Data-Retrievers",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 18 },
   "options": {
    "content": "# Operator Level\n\nData relevant to operators within a file since a single TXC file can contain multiple operators        "
   },
   "targets": [
    { "region": "default", "statistics": [ "Average" ] }
   ]
  },
  {
   "title": "BODS - Operators with No NOC",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": { "By Data Source": "bods" },
     "metricName": "NoNoc",
     "namespace": "FDBT/Reference-Data-Uploaders",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "BODS - Operators with Invalid NOCs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": { "By Data Source": "bods" },
     "metricName": "InvalidNoc",
     "namespace": "FDBT/Reference-Data-Uploaders",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  { "title": "TNDS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 29 },
   "options": {
    "content": "# File Level\n\nData relevant to the file as a whole         "
   },
   "targets": [
    { "region": "default", "statistics": [ "Average" ] }
   ]
  },
  {
   "title": "TNDS - Files Processed with Data",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": { "By Data Source": "tnds" },
     "metricName": "FilesProcessedWithData",
     "namespace": "FDBT/Reference-Data-Uploaders",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "TNDS - Files Processed with no Useable Data",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": { "By Data Source": "tnds" },
     "metricName": "FilesProcessedNoData",
     "namespace": "FDBT/Reference-Data-Uploaders",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "TNDS - Files Processed with no NOCs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": { "By Data Source": "tnds" },
     "metricName": "NoNOCsInFile",
     "namespace": "FDBT/Reference-Data-Uploaders",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "TNDS - Files Processed with Invalid NOCs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": { "By Data Source": "tnds" },
     "metricName": "InvalidNoc",
     "namespace": "FDBT/Reference-Data-Uploaders",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "TNDS - Files Processed with No Operator Data",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": { "By Data Source": "tnds" },
     "metricName": "NoOperatorData",
     "namespace": "FDBT/Reference-Data-Uploaders",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "TNDS - Files Processed with No Service Data",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": { "By Data Source": "tnds" },
     "metricName": "NoServiceDataInFile",
     "namespace": "FDBT/Reference-Data-Uploaders",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "TNDS - Files Processed with No Line Data",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": { "By Data Source": "tnds" },
     "metricName": "NoLineDataInFile",
     "namespace": "FDBT/Reference-Data-Uploaders",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "TNDS - Total Files Retrieved",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": { "By Data Source": "tnds" },
     "metricName": "TxcFilesCopied",
     "namespace": "FDBT/Reference-Data-Retrievers",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 46 },
   "options": {
    "content": "# Operator Level\n\nData relevant to operators within a file since a single TXC file can contain multiple operators        "
   },
   "targets": [
    { "region": "default", "statistics": [ "Average" ] }
   ]
  },
  {
   "title": "TNDS - Operators with No NOC",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": { "By Data Source": "tnds" },
     "metricName": "NoNoc",
     "namespace": "FDBT/Reference-Data-Uploaders",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "TNDS - Operators with Invalid NOCs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": { "By Data Source": "tnds" },
     "metricName": "InvalidNoc",
     "namespace": "FDBT/Reference-Data-Uploaders",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  }
 ]
}