# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:

    branches:
      only:
        - develop

    docker:
      - image: circleci/node:latest

    steps:
      - checkout

# Steps for data-aggregator
      - restore_cache:
          keys:
            - dependencies-cache-data-aggregator-{{ checksum "fares-data-build-tool/data-aggregator/package.json" }}
            - dependencies-cache-data-aggregator

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            pwd
            cd fares-data-build-tool/data-aggregator
            sudo npm install
      
      - run: 
          name: Run tests
          command: npm run test
           
      - run:
          name: Deploy application to tfn-test on aws 
          command: sls deploy --aws-profile tfn-test

      - save_cache:
          paths:
            - fares-data-build-tool/data-aggregator/node_modules
          key: dependencies-cache-data-aggregator-{{ checksum "fares-data-build-tool/data-aggregator/package.json" }}
      
 # Steps for netex-convertor       
      - restore_cache:
          keys:
            - dependencies-cache-netex-convertor-{{ checksum "fares-data-build-tool/netex-convertor/package.json" }}
            - dependencies-cache-netex-convertor

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            cd fares-data-build-tool/netex-convertor
            sudo npm install
      
      - run: 
          name: Run tests
          command: npm run test
           
      - run:
          name: Deploy application to tfn-test on aws 
          command: sls deploy --aws-profile tfn-test

      - save_cache:
          paths:
            - fares-data-build-tool/netex-convertor/node_modules

          key: dependencies-cache-netex-convertor-{{ checksum "fares-data-build-tool/netex-convertor/package.json" }}

  # Steps for ref-data-uploader      
      - restore_cache:
          keys:
            - dependencies-cache-ref-data-uploader-{{ checksum "fares-data-build-tool/ref-data-uploader/package.json" }}
            - dependencies-cache-ref-data-uploader
           
      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            cd fares-data-build-tool/ref-data-uploader
            sudo npm install
      
      - run: 
          name: Run tests
          command: npm run test
           
      - run:
          name: Deploy application to tfn-test on aws 
          command: sls deploy --aws-profile tfn-test

      - save_cache:
          paths:
            - fares-data-build-tool/ref-data-uploader/node_modules
          key: dependencies-cache-ref-data-uploader-{{ checksum "fares-data-build-tool/ref-data-uploader/package.json" }}

  #Steps for odh-uploader      
      - restore_cache:
          keys:
            - dependencies-cache-odh-uploader-{{ checksum "fares-data-build-tool/odh-uploader/package.json" }}
            - dependencies-cache-odh-uploader

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            cd fares-data-build-tool/odh-uploader
            sudo npm install
      
      - run: 
          name: Run tests
          command: npm run test
           
      - run:
          name: Deploy application to tfn-test on aws 
          command: sls deploy --aws-profile tfn-test

      - save_cache:
          paths:
            - fares-data-build-tool/odh-uploader/node_modules
          key: dependencies-cache-odh-uploader-{{ checksum "fares-data-build-tool/odh-uploader/package.json" }}
        