version: 2.1
orbs:
  semver-orb: tv2norge/semver-orb@0.0.1

jobs:
  checkout-repo:
    docker:
      - image: circleci/node:latest
    working_directory: ~/project
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/project
          paths:
            - "*"

  build-netex-convertor:
    docker:
      - image: circleci/node:latest
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          command: |
            cd netex-convertor
            npm install
            npm run build
      - persist_to_workspace:
          root: ~/project
          paths:
            - "netex-convertor/node_modules"

  test-netex-convertor:
    docker:
      - image: circleci/node:latest
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          command: |
            cd netex-convertor
            npm run test

  deploy-test-netex-convertor:
    docker:
      - image: circleci/node:latest
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          command: |
            sudo npm i -g serverless
            cd netex-convertor 
            export SLS_DEBUG="*" && sls deploy
            echo "Finished deploy"

  build-odh-uploader:
    docker:
      - image: circleci/node:latest
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          command: |
            cd odh-uploader
            npm install
            npm run build
      - persist_to_workspace:
          root: ~/project
          paths:
            - "odh-uploader/node_modules"

  test-odh-uploader:
    docker:
      - image: circleci/node:latest
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          command: |
            cd odh-uploader
            npm run test

  deploy-test-odh-uploader:
    docker:
      - image: circleci/node:latest
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          command: |
            sudo npm i -g serverless
            cd odh-uploader 
            export SLS_DEBUG="*" && sls deploy
            echo "Finished deploy"

  build-naptan-uploader:
    docker:
      - image: circleci/node:latest
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          command: |
            cd naptan-uploader
            npm install
            npm run build
      - persist_to_workspace:
          root: ~/project
          paths:
            - "naptan-uploader/node_modules"

  test-naptan-uploader:
    docker:
      - image: circleci/node:latest
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          command: |
            cd naptan-uploader
            npm run test

  deploy-test-naptan-uploader:
    docker:
      - image: circleci/node:latest
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          command: |
            sudo npm i -g serverless
            cd naptan-uploader 
            export SLS_DEBUG="*" && sls deploy
            echo "Finished deploy"

  build-noc-uploader:
    docker:
      - image: circleci/node:latest
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          command: |
            cd noc-uploader
            npm install
            npm run build
      - persist_to_workspace:
          root: ~/project
          paths:
            - "noc-uploader/node_modules"

  test-noc-uploader:
    docker:
      - image: circleci/node:latest
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          command: |
            cd noc-uploader
            npm run test

  deploy-test-noc-uploader:
    docker:
      - image: circleci/node:latest
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          command: |
            sudo npm i -g serverless
            cd noc-uploader 
            export SLS_DEBUG="*" && sls deploy
            echo "Finished deploy"

  build-nptg-uploader:
    docker:
      - image: circleci/node:latest
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          command: |
            cd nptg-uploader
            npm install
            npm run build
      - persist_to_workspace:
          root: ~/project
          paths:
            - "nptg-uploader/node_modules"

  test-nptg-uploader:
    docker:
      - image: circleci/node:latest
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          command: |
            cd nptg-uploader
            npm run test

  deploy-test-nptg-uploader:
    docker:
      - image: circleci/node:latest
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          command: |
            sudo npm i -g serverless
            cd nptg-uploader 
            export SLS_DEBUG="*" && sls deploy
            echo "Finished deploy"

  build-tnds-uploader:
    docker:
      - image: circleci/node:latest
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          command: |
            cd tnds-uploader
            npm install
            npm run build
      - persist_to_workspace:
          root: ~/project
          paths:
            - "tnds-uploader/node_modules"

  test-tnds-uploader:
    docker:
      - image: circleci/node:latest
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          command: |
            cd tnds-uploader
            npm run test

  deploy-test-tnds-uploader:
    docker:
      - image: circleci/node:latest
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          command: |
            sudo npm i -g serverless
            cd tnds-uploader 
            export SLS_DEBUG="*" && sls deploy
            echo "Finished deploy"

  build-site:
    docker:
      - image: circleci/node:latest
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          command: |
            cd site
            npm install
            npm run build
      - persist_to_workspace:
          root: ~/project
          paths:
            - "site/node_modules"

  test-site:
    docker:
      - image: circleci/node:latest
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          command: |
            cd site
            npm run test

  deploy-test-site:
    docker:
      - image: circleci/node:latest
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          command: |
            sudo npm i -g serverless
            cd site
            export NODE_ENV='test' && export SLS_DEBUG="*" && sls deploy
            echo "Finished deploy"

  tag-test-release:
    executor: semver-orb/default
    steps:
      - add_ssh_keys:
          fingerprints:
            - "ae:c4:4d:60:42:28:19:e4:d3:c0:02:5e:98:96:cc:3b"
      - attach_workspace:
          at: ~/project
      - semver-orb/print
      - semver-orb/tagnext
      - semver-orb/export-tag
      - semver-orb/print

workflows:
  version: 2
  build-and-test-deliverable-one-lambdas:
    jobs:
      - checkout-repo:
          context: "tfn-aws"
          filters:
            branches:
              only: develop

      - build-netex-convertor:
          requires:
            - checkout-repo
          context: "tfn-aws"
          filters:
            branches:
              only: develop
      - test-netex-convertor:
          requires:
            - build-netex-convertor
          context: "tfn-aws"
          filters:
            branches:
              only: develop
      - deploy-test-netex-convertor:
          requires:
            - test-netex-convertor
          context: "tfn-aws"
          filters:
            branches:
              only: develop

      - build-odh-uploader:
          requires:
            - checkout-repo
          context: "tfn-aws"
          filters:
            branches:
              only: develop
      - test-odh-uploader:
          requires:
            - build-odh-uploader
          context: "tfn-aws"
          filters:
            branches:
              only: develop
      - deploy-test-odh-uploader:
          requires:
            - test-odh-uploader
          context: "tfn-aws"
          filters:
            branches:
              only: develop

      - build-naptan-uploader:
          requires:
            - checkout-repo
          context: "tfn-aws"
          filters:
            branches:
              only: develop
      - test-naptan-uploader:
          requires:
            - build-naptan-uploader
          context: "tfn-aws"
          filters:
            branches:
              only: develop
      - deploy-test-naptan-uploader:
          requires:
            - test-naptan-uploader
          context: "tfn-aws"
          filters:
            branches:
              only: develop

      - build-noc-uploader:
          requires:
            - checkout-repo
          context: "tfn-aws"
          filters:
            branches:
              only: develop
      - test-noc-uploader:
          requires:
            - build-noc-uploader
          context: "tfn-aws"
          filters:
            branches:
              only: develop
      - deploy-test-noc-uploader:
          requires:
            - test-noc-uploader
          context: "tfn-aws"
          filters:
            branches:
              only: develop

      - build-nptg-uploader:
          requires:
            - checkout-repo
          context: "tfn-aws"
          filters:
            branches:
              only: develop
      - test-nptg-uploader:
          requires:
            - build-nptg-uploader
          context: "tfn-aws"
          filters:
            branches:
              only: develop
      - deploy-test-nptg-uploader:
          requires:
            - test-nptg-uploader
          context: "tfn-aws"
          filters:
            branches:
              only: develop

      - build-tnds-uploader:
          requires:
            - checkout-repo
          context: "tfn-aws"
          filters:
            branches:
              only: develop
      - test-tnds-uploader:
          requires:
            - build-tnds-uploader
          context: "tfn-aws"
          filters:
            branches:
              only: develop
      - deploy-test-tnds-uploader:
          requires:
            - test-tnds-uploader
          context: "tfn-aws"
          filters:
            branches:
              only: develop
              
      - build-site:
          requires:
            - checkout-repo
          context: "tfn-aws"
          filters:
            branches:
              only: develop
      - test-site:
          requires:
            - build-site
          context: "tfn-aws"
          filters:
            branches:
              only: develop
      - deploy-test-site:
          requires:
            - test-site
          context: "tfn-aws"
          filters:
            branches:
              only: develop

      - tag-test-release:
          requires:
            - deploy-test-netex-convertor
            - deploy-test-odh-uploader
            - deploy-test-naptan-uploader
            - deploy-test-noc-uploader
            - deploy-test-nptg-uploader
            - deploy-test-tnds-uploader
            - deploy-test-site
          context: "tfn-aws"
          filters:
            branches:
              only: develop
