# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    branches:
      only:
        - master

    docker:
      - image: circleci/node:latest

    steps:
      - checkout

      # Steps for data-aggregator
      - restore_cache:
          keys:
            - dependencies-cache-data-aggregator-{{ checksum "data-aggregator/package.json" }}
            - dependencies-cache-data-aggregator

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            pwd
            ls -la
            cd data-aggregator
            sudo npm install

      - run:
          name: Run tests
          command: |
            pwd
            ls -la
            cd data-aggregator
            npm run test

      # - run:
      #     name: Deploy application to tfn-test on aws
      #     command: |
      #       pwd
      #       ls -la
      #       cd data-aggregator
      #       sls deploy --aws-profile tfn-test

      - save_cache:
          paths:
            - data-aggregator/node_modules
          key: dependencies-cache-data-aggregator-{{ checksum "data-aggregator/package.json" }}

      # Steps for netex-convertor
      - restore_cache:
          keys:
            - dependencies-cache-netex-convertor-{{ checksum "netex-convertor/package.json" }}
            - dependencies-cache-netex-convertor

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            cd netex-convertor
            sudo npm install

      - run:
          name: Run tests
          command: |
            pwd
            ls -la
            cd netex-convertor
            npm run test

      # - run:
      #     name: Deploy application to tfn-test on aws
      #     command: |
      #       pwd
      #       ls -la
      #       cd netex-convertor
      #       sls deploy --aws-profile tfn-test

      - save_cache:
          paths:
            - netex-convertor/node_modules

          key: dependencies-cache-netex-convertor-{{ checksum "netex-convertor/package.json" }}

      # Steps for ref-data-uploader
      - restore_cache:
          keys:
            - dependencies-cache-ref-data-uploader-{{ checksum "ref-data-uploader/package.json" }}
            - dependencies-cache-ref-data-uploader

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            cd ref-data-uploader
            sudo npm install

      - run:
          name: Run tests
          command: |
            pwd
            ls -la
            cd ref-data-uploader
            npm run test

      # - run:
      #     name: Deploy application to tfn-test on aws
      #     command: |
      #       pwd
      #       ls -la
      #       cd ref-data-uploader
      #       sls deploy --aws-profile tfn-test

      - save_cache:
          paths:
            - ref-data-uploader/node_modules
          key: dependencies-cache-ref-data-uploader-{{ checksum "ref-data-uploader/package.json" }}

      #Steps for odh-uploader
      - restore_cache:
          keys:
            - dependencies-cache-odh-uploader-{{ checksum "odh-uploader/package.json" }}
            - dependencies-cache-odh-uploader

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            cd odh-uploader
            sudo npm install

      - run:
          name: Run tests
          command: |
            pwd
            ls -la
            cd odh-uploader
            npm run test

      # - run:
      #     name: Deploy application to tfn-test on aws
      #     command: |
      #       pwd
      #       ls -la
      #       cd odh-uploader
      #       sls deploy --aws-profile tfn-test

      - save_cache:
          paths:
            - odh-uploader/node_modules
          key: dependencies-cache-odh-uploader-{{ checksum "odh-uploader/package.json" }}
