version: 2.1
orbs:
  semver-orb: tv2norge/semver-orb@0.0.1

jobs: 

  build-netex-convertor:
    docker:
      - image: circleci/node:latest
    working_directory: ~/project
    steps:
      - checkout
      - run:
          command: |
            cd netex-convertor
            npm install
            npm run build
      - persist_to_workspace:
          root: ~/project
          paths:
            - "*"

  test-netex-convertor:
    docker:
      - image: circleci/node:latest
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          command: |
            cd netex-convertor
            npm run test

  deploy-test-netex-convertor:
    docker:
      - image: circleci/node:latest
    working_directory: ~/project
    steps:
      - checkout
      - run:
          command: |
            sudo npm i -g serverless
            cd netex-convertor 
            npm install
            export SLS_DEBUG="*" && sls deploy
            echo "Finished deploy"

  build-odh-uploader:
    docker:
      - image: circleci/node:latest
    working_directory: ~/project
    steps:
      - checkout
      - run:
          command: |
            cd odh-uploader
            npm install
            npm run build

  test-odh-uploader:
    docker:
      - image: circleci/node:latest
    working_directory: ~/project
    steps:
      - checkout
      - run:
          command: |
            cd odh-uploader
            npm install
            npm run test

  deploy-test-odh-uploader:
    docker:
      - image: circleci/node:latest
    working_directory: ~/project
    steps:
      - checkout
      - run:
          command: |
            sudo npm i -g serverless
            cd odh-uploader 
            npm install
            export SLS_DEBUG="*" && sls deploy
            echo "Finished deploy"


  build-ref-data-uploader:
    docker:
      - image: circleci/node:latest
    working_directory: ~/project
    steps:
      - checkout
      - run:
          command: |
            cd ref-data-uploader
            npm install
            npm run build

  test-ref-data-uploader:
    docker:
      - image: circleci/node:latest
    working_directory: ~/project
    steps:
      - checkout
      - run:
          command: |
            cd ref-data-uploader
            npm install
            npm run test

  deploy-test-ref-data-uploader:
    docker:
      - image: circleci/node:latest
    working_directory: ~/project
    steps:
      - checkout
      - run:
          command: |
            sudo npm i -g serverless
            cd ref-data-uploader 
            npm install
            export SLS_DEBUG="*" && sls deploy
            echo "Finished deploy"

  build-site:
    docker:
      - image: circleci/node:latest
    working_directory: ~/project
    steps:
      - checkout
      - run:
          command: |
            cd site
            npm install
            npm run build

  test-site:
    docker:
      - image: circleci/node:latest
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            cd site
            npm install
            npm run test

  deploy-test-site:
    docker:
      - image: circleci/node:latest
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Deploy application to tfn-test on aws
          command: |
            sudo npm i -g serverless
            cd site
            npm install
            export NODE_ENV='test' && export SLS_DEBUG="*" && sls deploy
            echo "Finished deploy"

  tag-test-release:
    executor: semver-orb/default
    steps:
      - add_ssh_keys:
          fingerprints:
            - "82:dc:89:ad:e9:41:c9:bd:db:e7:c1:84:68:c6:da:35"
      - checkout
      - semver-orb/print
      - semver-orb/tagnext
      - semver-orb/export-tag
      - semver-orb/print

workflows:
  version: 2
  build-and-test-deliverable-one-lambdas:
    jobs:
      - build-netex-convertor:
          context: "tfn-aws"
          filters:
            branches:
              only: feature/TFN-165_circle_git_tag
      - test-netex-convertor:
          requires:
            - build-netex-convertor
          context: "tfn-aws"
          filters:
            branches:
              only: feature/TFN-165_circle_git_tag
      - deploy-test-netex-convertor:
          requires:
            - test-netex-convertor
          context: "tfn-aws"
          filters:
            branches:
              only: feature/TFN-165_circle_git_tag

      - build-odh-uploader:
          context: "tfn-aws"
          filters:
            branches:
              only: feature/TFN-165_circle_git_tag
      - test-odh-uploader:
          requires:
            - build-odh-uploader
          context: "tfn-aws"
          filters:
            branches:
              only: feature/TFN-165_circle_git_tag
      - deploy-test-odh-uploader:
          requires:
            - test-odh-uploader
          context: "tfn-aws"
          filters:
            branches:
              only: feature/TFN-165_circle_git_tag


      - build-ref-data-uploader:
          context: "tfn-aws"
          filters:
            branches:
              only: feature/TFN-165_circle_git_tag
      - test-ref-data-uploader:
          requires:
            - build-ref-data-uploader
          context: "tfn-aws"
          filters:
            branches:
              only: feature/TFN-165_circle_git_tag
      - deploy-test-ref-data-uploader:
          requires:
            - test-ref-data-uploader
          context: "tfn-aws"
          filters:
            branches:
              only: feature/TFN-165_circle_git_tag

      - build-site:
          context: "tfn-aws"
          filters:
            branches:
              only: feature/TFN-165_circle_git_tag
      - test-site:
          requires:
            - build-site
          context: "tfn-aws"
          filters:
            branches:
              only: feature/TFN-165_circle_git_tag
      - deploy-test-site:
          requires:
            - test-site
          context: "tfn-aws"
          filters:
            branches:
              only: feature/TFN-165_circle_git_tag

      - tag-test-release:
          requires:
            - deploy-test-netex-convertor
            - deploy-test-odh-uploader
            - deploy-test-ref-data-uploader
            - deploy-test-site
          context: "tfn-aws"
          filters:
            branches:
              only: feature/TFN-165_circle_git_tag
