version: 2.1
orbs:
  semver-orb: tv2norge/semver-orb@0.0.1

jobs:
  checkout-repo:
    docker:
      - image: circleci/node:latest
    working_directory: ~/project
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/project
          paths:
            - "*"

  build-and-test-netex-convertor:
    docker:
      - image: circleci/node:latest
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          command: |
            echo "Starting build"
            cd netex-output
            cd netex-convertor
            npm install
            npm run build
            echo "Running tests"
            npm run test
      - persist_to_workspace:
          root: ~/project
          paths:
            - "netex-output/netex-convertor/node_modules"

  build-and-test-odh-uploader:
    docker:
      - image: circleci/node:latest
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          command: |
            echo "Starting build"
            cd netex-output
            cd odh-uploader
            npm install
            npm run build
            echo "Running tests"
            npm run test          
      - persist_to_workspace:
          root: ~/project
          paths:
            - "netex-output/odh-uploader/node_modules"

  deploy-netex-output-resources:
    docker:
      - image: circleci/node:latest
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          command: |
            echo "Deploying..."
            sudo npm i -g serverless
            cd netex-output
            export SLS_DEBUG="*" && sls deploy
            echo "Finished deploy"

  build-and-test-naptan-uploader:
    docker:
      - image: circleci/node:latest
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          command: |
            echo "Starting build"
            cd reference-data
            cd naptan-uploader
            npm install
            npm run build
            echo "Running tests"
            npm run test
      - persist_to_workspace:
          root: ~/project
          paths:
            - "reference-data/napta/uploader/node_modules"

  build-and-test-noc-uploader:
    docker:
      - image: circleci/node:latest
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          command: |
            echo "Starting build"
            cd reference-data
            cd noc-uploader
            npm install
            npm run build
            echo "Running tests"
            npm run test
      - persist_to_workspace:
          root: ~/project
          paths:
            - "reference-data/node_modules"

  build-and-test-nptg-uploader:
    docker:
      - image: circleci/node:latest
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          command: |
            echo "Starting build"
            cd reference-data
            cd nptg-uploader
            npm install
            npm run build
            echo "Running tests"
            npm run test
      - persist_to_workspace:
          root: ~/project
          paths:
            - "reference-data/node_modules"

  build-and-test-tnds-uploader:
    docker:
      - image: circleci/node:latest
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          command: |
            echo "Starting build"
            cd reference-data
            cd tnds-uploader
            npm install
            npm run build
            echo "Running tests"
            npm run test
      - persist_to_workspace:
          root: ~/project
          paths:
            - "reference-data/node_modules"

  deploy-reference-data-resources:
    docker:
      - image: circleci/node:latest
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          command: |
            sudo npm i -g serverless
            cd reference-data
            export SLS_DEBUG="*" && sls deploy
            echo "Finished deploy"

  build-and-test-site:
    docker:
      - image: circleci/node:latest
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          command: |
            echo "Starting build"
            cd site
            npm install
            npm run build
            echo "Running tests"
            npm run test
      - persist_to_workspace:
          root: ~/project
          paths:
            - "site/node_modules"

  deploy-site:
    docker:
      - image: circleci/node:latest
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          command: |
            echo "Deploying..."
            sudo npm i -g serverless
            cd site
            export NODE_ENV='test' && export SLS_DEBUG="*" && sls deploy
            echo "Finished deploy"

  tag-test-release:
    executor: semver-orb/default
    steps:
      - add_ssh_keys:
          fingerprints:
            - "82:dc:89:ad:e9:41:c9:bd:db:e7:c1:84:68:c6:da:35"
      - attach_workspace:
          at: ~/project
      - semver-orb/print
      - semver-orb/tagnext
      - semver-orb/export-tag
      - semver-orb/print

workflows:
  version: 2
  build-test-and-deploy-deliverable-one-lambdas:
    jobs:
      - checkout-repo:
          context: "tfn-aws"
          filters:
            branches:
              only: develop

      - build-and-test-netex-convertor:
          requires:
            - checkout-repo
          context: "tfn-aws"
          filters:
            branches:
              only: develop
      - build-and-test-odh-uploader:
          requires:
            - checkout-repo
          context: "tfn-aws"
          filters:
            branches:
              only: develop
      - deploy-netex-output-resources:
          requires:
            - build-and-test-netex-convertor
            - build-and-test-odh-uploader
          context: "tfn-aws"
          filters:
            branches:
              only: develop              

      - build-and-test-naptan-uploader:
          requires:
            - checkout-repo
          context: "tfn-aws"
          filters:
            branches:
              only: develop
      - build-and-test-noc-uploader:
          requires:
            - checkout-repo
          context: "tfn-aws"
          filters:
            branches:
              only: develop
      - build-and-test-nptg-uploader:
          requires:
            - checkout-repo
          context: "tfn-aws"
          filters:
            branches:
              only: develop
      - build-and-test-tnds-uploader:
          requires:
            - checkout-repo
          context: "tfn-aws"
          filters:
            branches:
              only: develop
      - deploy-reference-data-resources:
          requires:
            - build-and-test-naptan-uploader
            - build-and-test-noc-uploader
            - build-and-test-nptg-uploader
            - build-and-test-tnds-uploader
          context: "tfn-aws"
          filters:
            branches:
              only: develop
              
      - build-and-test-site:
          requires:
            - checkout-repo
          context: "tfn-aws"
          filters:
            branches:
              only: develop
      - deploy-site:
          requires:
            - build-and-test-site
          context: "tfn-aws"
          filters:
            branches:
              only: develop

      - tag-test-release:
          requires:
            - deploy-netex-output-resources
            - deploy-reference-data-resources
            - deploy-site
          context: "tfn-aws"
          filters:
            branches:
              only: develop
