service: reference-data-service-uploaders

provider:
  name: aws
  runtime: python3.8
  region: eu-west-2
  stage: ${opt:stage, 'test'}
  vpc:
    securityGroupIds:
      - Fn::ImportValue: ${self:provider.stage}:ReferenceDataUploaderLambdaSG
    subnetIds:
      - Fn::ImportValue: ${self:provider.stage}:PrivateSubnetA
      - Fn::ImportValue: ${self:provider.stage}:PrivateSubnetB
  environment:
    RDS_HOST:
      Fn::ImportValue: ${self:provider.stage}:RdsHostName
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ssm:GetParameter"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
        - "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::fdbt-csv-reference-data-${self:provider.stage}/*"
        - "arn:aws:s3:::fdbt-xml-reference-data-${self:provider.stage}/*"

plugins:
  - serverless-python-requirements
  - serverless-plugin-aws-alerts

custom:
  pythonRequirements:
    dockerizePip: false
  alerts:
    dashboards: false
    topics:
      ok:
        topic: reference-data-service-uploaders-ok-topic
        notifications:
          - protocol: lambda
            endpoint:
              Fn::ImportValue: ${self:provider.stage}:SlackAlertsFunctionArn
      alarm:
        topic: reference-data-service-uploaders-alarm-topic
        notifications:
          - protocol: lambda
            endpoint:
              Fn::ImportValue: ${self:provider.stage}:SlackAlertsFunctionArn
    alarms:
      - functionThrottles
      - functionErrors
      - functionInvocations
      - functionDuration

functions:
  CsvUploader:
    handler: csv_uploader/csv_uploader_handler.handler
    module: csv_uploader
    timeout: 60
    memorySize: 256
    events:
      - s3: fdbt-csv-reference-data-${self:provider.stage}
        event: s3:ObjectCreated:*
    alarms:
      - name: functionDuration
        threshold: 50000
        treatMissingData: notBreaching
      - name: functionThrottles
        treatMissingData: notBreaching
      - name: functionErrors
        treatMissingData: notBreaching
      - name: functionInvocations
        treatMissingData: notBreaching

  XmlUploader:
    handler: xml_uploader/xml_uploader_handler.handler
    module: xml_uploader
    timeout: 60
    memorySize: 1024
    events:
      - s3: fdbt-xml-reference-data-${self:provider.stage}
        event: s3:ObjectCreated:*
    reservedConcurrency: 40
    alarms:
      - name: functionDuration
        threshold: 50000
        treatMissingData: notBreaching
      - name: functionThrottles
        threshold: 1000
        treatMissingData: notBreaching
      - name: functionErrors
        treatMissingData: notBreaching
      - name: functionInvocations
        threshold: 5000
        treatMissingData: notBreaching

package:
  include:
    - ./csv-uploader/*
    - ./xml-uploader/*
  exclude:
    - ./node_modules/**
