{
 "title": "Business Intelligence",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "NeTEx per day",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expression": "fields @timestamp, @message\n| sort @timestamp desc\n| filter @message like /NeTEx generation complete/\n| stats count() by bin(1d)",
     "logGroupNames": [
      "/aws/lambda/netex-output-service-prod-NetexConvertor"
     ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [ "bin(1d)" ]
    }
   ]
  },
  {
   "title": "NeTEx created by type",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expression": "fields @timestamp, @message\n| sort @timestamp desc\n| parse @message \"NeTEx generation complete for type *\" as type\n| filter ispresent(type)\n| stats count() by type",
     "logGroupNames": [
      "/aws/lambda/netex-output-service-prod-NetexConvertor"
     ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [ "type" ]
    }
   ]
  },
  {
   "title": "Total NeTEx",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expression": "fields @timestamp, @message\n| sort @timestamp desc\n| filter @message like /NeTEx generation complete/\n| stats count()",
     "logGroupNames": [
      "/aws/lambda/netex-output-service-prod-NetexConvertor"
     ],
     "namespace": "FDBT/Netex-Validator",
     "queryMode": "Logs",
     "region": "default"
    }
   ]
  },
  {
   "title": "Total Registrations",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expression": "fields @timestamp, @message\n| sort @timestamp desc\n| filter @message like /registration successful/\n| stats count()",
     "logGroupNames": [ "fdbt-site-prod" ],
     "namespace": "FDBT/Netex-Validator",
     "queryMode": "Logs",
     "region": "default"
    }
   ]
  },
  {
   "title": "Started Transactions",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "metricName": "startedTransactions", "namespace": "FDBT/Site", "region": "default", "statistics": [ "Sum" ] }
   ]
  }
 ]
}