{
 "title": "KPI",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "environment", "query": "metrics(FDBT/Netex-Output)" }
  ]
 },
 "panels": [
  {
   "title": "Site ALB response time (Average)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dimensions": {
      "LoadBalancer": "app/FDBT-Publi-984WV6WVQ5BY/d90fa10cb3799dc0",
      "TargetGroup": "targetgroup/fdbt-site-tg-prod/21e1e60f2bf239d0"
     },
     "metricName": "TargetResponseTime",
     "namespace": "AWS/ApplicationELB",
     "region": "eu-west-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Site ALB response time (95th percentile)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dimensions": {
      "LoadBalancer": "app/FDBT-Publi-984WV6WVQ5BY/d90fa10cb3799dc0",
      "TargetGroup": "targetgroup/fdbt-site-tg-prod/21e1e60f2bf239d0"
     },
     "metricName": "TargetResponseTime",
     "namespace": "AWS/ApplicationELB",
     "region": "eu-west-2",
     "statistics": [ "p95" ]
    }
   ]
  },
  {
   "title": "Total NeTEx",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expression": "fields @timestamp, @message\n| sort @timestamp desc\n| filter @message like /NeTEx generation complete/\n| stats count()",
     "logGroupNames": [
      "/aws/lambda/netex-output-service-prod-NetexConvertor"
     ],
     "namespace": "FDBT/Netex-Validator",
     "queryMode": "Logs",
     "region": "default"
    }
   ]
  },
  {
   "title": "Started Transactions",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "metricName": "startedTransactions", "namespace": "FDBT/Site", "region": "default", "statistics": [ "Sum" ] }
   ]
  }
 ]
}