AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template for WAF resources in PreProd and Prod

Parameters:
  Stage:
    Type: String
    AllowedValues:
      - preprod
      - prod

  ProductName:
    Type: String
    Default: fdbt

Resources:
  SiteAccessAcl:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: !Sub ${ProductName}-waf-site-access-${Stage}
      Scope: CLOUDFRONT
      Description: Restricts access to site
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: RestrictAccessMetric
      Rules:
        - Name: BodySizeRestriction
          Priority: 0
          Statement:
            AndStatement:
              Statements:
                - SizeConstraintStatement:
                    FieldToMatch:
                      Body: {}
                    ComparisonOperator: GT
                    Size: 8192
                    TextTransformations:
                      - Priority: 0
                        Type: NONE
                - NotStatement:
                    Statement:
                      ByteMatchStatement:
                        SearchString: /api/
                        FieldToMatch:
                          UriPath: {}
                        TextTransformations:
                          - Priority: 0
                            Type: NONE
                        PositionalConstraint: STARTS_WITH
          Action:
            Block: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: BodySize
        - Name: AWS-AWSManagedRulesAmazonIpReputationList
          Priority: 1
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesAmazonIpReputationList
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWS-AWSManagedRulesAmazonIpReputationList
        - Name: AWS-AWSManagedRulesCommonRuleSet
          Priority: 2
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
              ExcludedRules:
                - Name: SizeRestrictions_BODY # handled by BodySizeRestriction
                - Name: NoUserAgent_HEADER # allow Cypress tests to run
                - Name: CrossSiteScripting_BODY # blocking some legitimate requests - see CFD-571
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWS-AWSManagedRulesCommonRuleSet

Outputs:
  WafAclArn:
    Value: !GetAtt SiteAccessAcl.Arn
