version: 2.1
orbs:
  semver-orb: tv2norge/semver-orb@0.0.1

jobs:
  checkout-repo:
    docker:
      - image: circleci/node:12
    working_directory: ~/project
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/project
          paths:
            - "*"

  build-site:
    docker:
      - image: circleci/node:12
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          command: |
            echo "Starting build"
            npm install
            npm run build
      - persist_to_workspace:
          root: ~/project
          paths:
            - "node_modules"

  test-site:
    docker:
      - image: circleci/node:12
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          command: |
            echo "Running tests"
            npm run test:ci

  lint-site:
    docker:
      - image: circleci/node:12
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          command: |
            echo "Linting site"
            npm run lint

  deploy-site-to-test:
    docker:
      - image: circleci/node:12
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          command: |
            echo "Deploying..."
            sudo npm i -g serverless
            export NODE_ENV='test' && export SLS_DEBUG="*" && sls deploy
            echo "Finished deploy"

workflows:
  version: 2
  build-test-and-deploy-site:
    jobs:
      - checkout-repo:
          filters:
            branches:
              only: develop
      - build-site:
          requires:
            - checkout-repo
          filters:
            branches:
              only: develop
      - test-site:
          requires:
            - build-site
          filters:
            branches:
              only: develop
      - lint-site:
          requires:
            - build-site
          filters:
            branches:
              only: develop
      - deploy-site-to-test:
          requires:
            - test-site
            - lint-site
          context: "tfn-aws"
          filters:
            branches:
              only: develop
