AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template for CloudTrail resources

Parameters:
  Stage:
    Type: String
    AllowedValues:
      - test
      - preprod
      - prod

Resources:
  Trail:
    Type: AWS::CloudTrail::Trail
    Properties:
      EnableLogFileValidation: true
      IncludeGlobalServiceEvents: true
      IsLogging: true
      IsMultiRegionTrail: true
      S3BucketName: tfn-audit-trails
      TrailName: !Sub fdbt-audit-trail-${Stage}
