AWSTemplateFormatVersion: "2010-09-09"

Description: "CloudFormation template for IAM resources"

Parameters:
  Stage:
    Type: String
    AllowedValues:
      - test
      - preprod
      - prod

Resources:
  AdminRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - 827855331226
            Action:
              - "sts:AssumeRole"
            Condition:
              Bool:
                aws:MultiFactorAuthPresent: true
      RoleName: !Sub tfn-admin-${Stage}-${AWS::Region}
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  ReadOnlyRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - 827855331226
            Action:
              - "sts:AssumeRole"
            Condition:
              Bool:
                aws:MultiFactorAuthPresent: true
      RoleName: !Sub tfn-readonly-${Stage}-${AWS::Region}
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess

  BillingRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - 827855331226
            Action:
              - "sts:AssumeRole"
            Condition:
              Bool:
                aws:MultiFactorAuthPresent: true
      RoleName: !Sub tfn-billing-${Stage}-${AWS::Region}
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/job-function/Billing

  EcsTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [ecs-tasks.amazonaws.com]
            Action: ["sts:AssumeRole"]
      Path: /
      Policies:
        - PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "s3:GetObject"
                  - "s3:PutObject"
                Resource:
                  - !Sub arn:aws:s3:::fdbt-user-data-${Stage}/*
              - Effect: Allow
                Action:
                  - "s3:PutObject"
                Resource:
                  - !Sub arn:aws:s3:::fdbt-raw-user-data-${Stage}/*
                  - !Sub arn:aws:s3:::fdbt-matching-data-${Stage}/*
              - Effect: Allow
                Action:
                  - "dynamodb:BatchGetItem"
                  - "dynamodb:GetItem"
                  - "dynamodb:Query"
                Resource: "*"
          PolicyName: allow-s3-dynamo-access

  EcsTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [ecs-tasks.amazonaws.com]
            Action: ["sts:AssumeRole"]
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  Policy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      Description: "Policy for cicd accounts"
      Path: /
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "s3:*"
              - "logs:*"
              - "cloudformation:*"
              - "iam:*"
              - "cloudfront:*"
              - "cloudwatch:*"
              - "waf:*"
              - "route53:*"
              - "lambda:*"
              - "waf-regional:*"
              - "acm:DescribeCertificate"
              - "acm:GetCertificate"
              - "acm:ListTagsForCertificate"
              - "acm:ListCertificates"
              - "apigateway:*"
              - "dynamodb:*"
              - "events:*"
              - "ecs:*"
            Resource: "*"

  NextJsLambdaPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      Description: "Policy for lambda@edge execution role"
      Path: /
      ManagedPolicyName: fdbt-nextjs-lambda-policy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "logs:CreateLogGroup"
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
            Resource: "*"
          - Effect: Allow
            Action:
              - "dynamodb:GetItem"
              - "dynamodb:BatchGetItem"
              - "dynamodb:PutItem"
              - "dynamodb:Scan"
              - "dynamodb:Query"
              - "dynamodb:UpdateItem"
              - "s3:PutObject"
              - "s3:GetObject"
            Resource: "*"

  Group:
    Type: "AWS::IAM::Group"
    Properties:
      GroupName: "fdbt-cicd-group"
      ManagedPolicyArns:
        - !Ref Policy

  User:
    Type: "AWS::IAM::User"
    Properties:
      UserName: "fdbt-circleci-user"
      Groups:
        - !Ref Group

Outputs:
  EcsTaskRoleArn:
    Value: !GetAtt EcsTaskRole.Arn
    Export:
      Name: !Sub ${Stage}:EcsTaskRoleArn
  EcsTaskExecutionRoleArn:
    Value: !GetAtt EcsTaskExecutionRole.Arn
    Export:
      Name: !Sub ${Stage}:EcsTaskExecutionRoleArn
