AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation template for Route53 resources"

Parameters:
  Stage:
    Type: String
    AllowedValues:
      - test
      - preprod
      - prod
  InternalDomainName:
    Description: "Domain name for internal hosted zone"
    Type: String
  ExternalDomainName:
    Description: "Domain name for external hosted zone"
    Type: String

Resources:
  PrivateHostedZone:
    Type: AWS::Route53::HostedZone
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: !Ref InternalDomainName
      VPCs:
        - VPCId:
            Fn::ImportValue: !Sub ${Stage}:VpcId
          VPCRegion: !Ref AWS::Region

  ExternalHostedZone:
    Type: AWS::Route53::HostedZone
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: !Ref ExternalDomainName
      VPCs:
        - VPCId:
            Fn::ImportValue: !Sub ${Stage}:VpcId
          VPCRegion: !Ref AWS::Region

Outputs:
  PrivateHostedZoneId:
    Value: !Ref PrivateHostedZone
    Export:
      Name: !Sub ${Stage}:PrivateHostedZoneId

  ExternalHostedZoneId:
    Value: !Ref ExternalHostedZone
    Export:
      Name: !Sub ${Stage}:ExternalHostedZoneId

  InternalDomain:
    Value: !Ref InternalDomainName
    Export:
      Name: !Sub ${Stage}:InternalDomainName

  ExternalDomain:
    Value: !Ref ExternalDomainName
    Export:
      Name: !Sub ${Stage}:ExternalDomainName
