AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template for WAF resources

Parameters:
  Stage:
    Type: String
    AllowedValues:
      - test
      - preprod
      - prod

  ProductName:
    Type: String
    Default: fdbt

  IwIpSetList:
    Type: CommaDelimitedList
    Default: ""

  TfnIpSetList:
    Type: CommaDelimitedList
    Default: ""

  TesterIpSetList:
    Type: CommaDelimitedList
    Default: ""

Conditions:
  IsTest: !Equals [!Ref Stage, "test"]
  IsNotTest: !Not [!Equals [!Ref Stage, "test"]]

Resources:
  IwIpSet:
    Type: AWS::WAFv2::IPSet
    Condition: IsTest
    Properties:
      Description: IP Set for Infinity Works office
      Name: IwIpSet
      Scope: REGIONAL
      IPAddressVersion: IPV4
      Addresses: !Ref IwIpSetList

  TfnIpSet:
    Type: AWS::WAFv2::IPSet
    Condition: IsTest
    Properties:
      Description: IP Set for TFN offices
      Name: TfnIpSet
      Scope: REGIONAL
      IPAddressVersion: IPV4
      Addresses: !Ref TfnIpSetList

  TesterIpSet:
    Type: AWS::WAFv2::IPSet
    Condition: IsTest
    Properties:
      Description: IP Set for testers of the tool
      Name: TesterIpSet
      Scope: REGIONAL
      IPAddressVersion: IPV4
      Addresses: !Ref TesterIpSetList

  CiIpSet:
    Type: AWS::WAFv2::IPSet
    Condition: IsTest
    Properties:
      Description: IP Set for CI
      Name: CiIpSet
      Scope: REGIONAL
      IPAddressVersion: IPV4
      Addresses: []

  PersonalUserIpSet:
    Type: AWS::WAFv2::IPSet
    Condition: IsTest
    Properties:
      Description: Personal IPs for IW, TFN and DFT users of the tool
      Name: PersonalUserIpSet
      Scope: REGIONAL
      IPAddressVersion: IPV4
      Addresses: []

  RestrictAccessAcl:
    Type: AWS::WAFv2::WebACL
    Condition: IsTest
    Properties:
      Name: !Sub ${ProductName}-waf-restrictaccess-${Stage}
      Scope: REGIONAL
      Description: Restricts access to Infinity Works, TFN and external testers
      DefaultAction:
        Block: {}
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: RestrictAccessMetric
      Rules:
        - Name: AllowIw
          Action:
            Allow: {}
          Priority: 0
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AllowIwRuleMetric
          Statement:
            IPSetReferenceStatement:
              Arn: !GetAtt IwIpSet.Arn
        - Name: AllowTfn
          Action:
            Allow: {}
          Priority: 1
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AllowTfnRuleMetric
          Statement:
            IPSetReferenceStatement:
              Arn: !GetAtt TfnIpSet.Arn
        - Name: AllowTesters
          Action:
            Allow: {}
          Priority: 2
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AllowTestersRuleMetric
          Statement:
            IPSetReferenceStatement:
              Arn: !GetAtt TesterIpSet.Arn
        - Name: AllowCi
          Action:
            Allow: {}
          Priority: 3
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AllowCiRuleMetric
          Statement:
            IPSetReferenceStatement:
              Arn: !GetAtt CiIpSet.Arn
        - Name: AllowPersonalUserIP
          Action:
            Allow: {}
          Priority: 4
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AllowPersonalUserIPRuleMetric
          Statement:
            IPSetReferenceStatement:
              Arn: !GetAtt PersonalUserIpSet.Arn

  DefaultAcl:
    Type: AWS::WAFv2::WebACL
    Condition: IsNotTest
    Properties:
      Name: !Sub ${ProductName}-waf-default-${Stage}
      Scope: REGIONAL
      Description: Default ACL with no restrictions
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: DefaultAccessMetric

  WafAssociation:
    Type: "AWS::WAFv2::WebACLAssociation"
    Properties:
      ResourceArn:
        Fn::ImportValue: !Sub ${Stage}:LoadbalancerArn
      WebACLArn:
        !If [IsTest, !GetAtt RestrictAccessAcl.Arn, !GetAtt DefaultAcl.Arn]
