service: circleci

provider:
  name: aws
  region: eu-west-2
  stage: ${opt:stage, 'test'}

resources: 
  Resources: 
    Policy:
      Type: "AWS::IAM::ManagedPolicy"
      Properties: 
        Description: "Policy for cicd accounts"
        Path: /
        PolicyDocument:
          Version: "2012-10-17"
          Statement: 
            - Effect: Allow
              Action: 
                - 's3:*'
                - 'logs:*'
                - 'cloudformation:*'
                - 'iam:*'
                - 'cloudfront:*'
                - 'cloudwatch:*'
                - 'waf:*'
                - 'route53:*'
                - 'lambda:*'
                - 'waf-regional:*'
                - 'acm:DescribeCertificate'
                - 'acm:GetCertificate'
                - 'acm:ListTagsForCertificate'
                - 'acm:ListCertificates'
                - 'apigateway:*'
                - 'dynamodb:*'
              Resource: '*'
    Group:
      Type: 'AWS::IAM::Group'
      Properties:
        GroupName: 'cicd'
        ManagedPolicyArns: 
          - !Ref Policy
    User:
      Type: 'AWS::IAM::User'
      Properties:
        UserName: "circleci"
        Groups: 
          - !Ref Group
    Keys:
      Type: 'AWS::IAM::AccessKey'
      Properties:
        UserName: !Ref User
  Outputs:
    AccessKey:
      Value: !Ref Keys
      Description: AWSAccessKeyId of new user
    SecretKey:
      Value: !GetAtt 
        - Keys
        - SecretAccessKey
      Description: AWSSecretKey of new user