name: update_lambda

# Were we can define the inputs that our action will accept
inputs:
  repo:
    required: true
  lambda:
    required: true
  environment:
    required: true

runs:
  using: "composite"
  steps:

  - name: Zip folder
    shell: bash
    run: |
      cd repos/${{ inputs.repo }}/dist/${{ inputs.lambda }}-${{ inputs.environment }}
      zip -r ${{ inputs.lambda }}-${{ inputs.environment }}.zip index.js*

  - name: Push up zip file to Lambda
    shell: bash
    run: |
      cd repos/${{ inputs.repo }}/dist/${{ inputs.lambda }}-${{ inputs.environment }}
      aws lambda update-function-code --function-name ${{ inputs.lambda }}-${{ inputs.environment }} --zip-file fileb://${{ inputs.lambda }}-${{ inputs.environment }}.zip
