declare module 'govuk-react';
declare module '@govuk-react/top-nav';
declare module '@govuk-react/heading';
declare module '@govuk-react/page';
declare module '@govuk-react/table';
declare module '@govuk-react/button';
declare module '@govuk-react/loading-box';
declare module '@govuk-react/details';
declare module 'react-easy-bar-chart';
