
service: tnds-uploader

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-2
  stage: ${opt:stage, 'test'}


plugins:
  - serverless-plugin-typescript
  - serverless-s3-local
  - serverless-dynamodb-local
  - serverless-offline


functions:
  s3hook:
    handler: handler.s3hook
    events: 
      - s3: fdbt-test-tnds-data
        event: s3:ObjectCreated:*


package:
  exclude:
    - node_modules/**/*
  include:
    handler.ts


resources:
  Resources:
    servicesTable: 
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Services
        AttributeDefinitions:
          - AttributeName: "NationalOperatorCode"
            AttributeType: "S"
          - AttributeName: "LineName"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "NationalOperatorCode"
            KeyType: "HASH"
          - AttributeName: "LineName"
            KeyType: "RANGE"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    tndsTable: 
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TNDS
        AttributeDefinitions:
          - AttributeName: "FileName"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "FileName"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1


# The below custom section is for local testing of dynamodb using serverless-dynamodb-local.
custom:
  dynamodb:
    stages:
      - test
    start:
      port: 9100
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
    
    seed:
      domain:
        sources:
          - table: Services
            sources: [./.dynamodb/seededTestData/dummy_services_data.json]
          - table: TNDS
            sources: [./.dynamodb/seededTestData/dummy_tnds_data.json]

      convertEmptyValues: true