service: naptan-uploader

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-2
  stage: ${opt:stage, 'test'}


plugins:
  - serverless-plugin-typescript
  - serverless-s3-local
  - serverless-dynamodb-local
  - serverless-offline


functions:
  s3hook:
    handler: handler.s3hook
    events: 
      - s3: fdbt-${self:provider.stage}-naptan-ref-data
        event: s3:ObjectCreated:*

package:
  exclude:
    - node_modules/**/*
  include:
    handler.ts


resources: 
  Resources:
    naptanTable: 
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Stops
        AttributeDefinitions:
          - AttributeName: "ATCOCode"
            AttributeType: "N"
        KeySchema:
          - AttributeName: "ATCOCode"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1


# The below custom section is for local testing of dynamodb using serverless-dynamodb-local.
custom:
  dynamodb:
    stages:
      - test
    start:
      port: 9100
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
    
    seed:
      domain:
        sources:
          - table: Stops
            sources: [./.dynamodb/dummy_naptan_data.json]

      convertEmptyValues: true