AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template for CloudTrail resources

Resources:
  Trail:
    Type: AWS::CloudTrail::Trail
    Properties:
      EnableLogFileValidation: true
      IncludeGlobalServiceEvents: true
      IsLogging: true
      IsMultiRegionTrail: true
      S3BucketName: cfd-audit-trails
      TrailName: fdbt-audit-trail-core
