AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template for IAM resources

Resources:
  CircleCiPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Policy for cicd accounts
      ManagedPolicyName: circleci-access
      Path: /
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "ecr:*"
            Resource: "*"

  CircleCiGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: fdbt-core-circleci-group
      ManagedPolicyArns:
        - !Ref CircleCiPolicy

  CircleCiUser:
    Type: AWS::IAM::User
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      UserName: fdbt-core-circleci-user
      Groups:
        - !Ref CircleCiGroup
