AWSTemplateFormatVersion: 2010-09-09

Description: CloudFormation template for IAM resources

Parameters:
  TestAccountId:
    Type: String
  PreProdAccountId:
    Type: String
  ProdAccountId:
    Type: String

Resources:
  ManageOwnUserPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Policy to allow users to manage their own account
      Path: /
      ManagedPolicyName: allow-manage-user
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "iam:GetAccountPasswordPolicy"
              - "iam:GetAccountSummary"
              - "iam:ListAccountAliases"
              - "iam:ListUsers"
              - "iam:ListVirtualMFADevices"
            Resource: "*"
          - Effect: Allow
            Action:
              - "iam:ChangePassword"
              - "iam:CreateAccessKey"
              - "iam:CreateLoginProfile"
              - "iam:DeleteAccessKey"
              - "iam:DeleteLoginProfile"
              - "iam:DeleteSigningCertificate"
              - "iam:DeleteSSHPublicKey"
              - "iam:GetLoginProfile"
              - "iam:GetSSHPublicKey"
              - "iam:ListAccessKeys"
              - "iam:ListSigningCertificates"
              - "iam:ListSSHPublicKeys"
              - "iam:UpdateAccessKey"
              - "iam:UpdateLoginProfile"
              - "iam:UpdateSigningCertificate"
              - "iam:UpdateSSHPublicKey"
              - "iam:UploadSigningCertificate"
              - "iam:UploadSSHPublicKey"
            Resource: "arn:aws:iam::*:user/${aws:username}"
          - Effect: Allow
            Action:
              - "iam:ListMFADevices"
            Resource:
              - "arn:aws:iam::*:mfa/*"
              - "arn:aws:iam::*:user/${aws:username}"
          - Effect: Allow
            Action:
              - "iam:CreateVirtualMFADevice"
              - "iam:DeactivateMFADevice"
              - "iam:DeleteVirtualMFADevice"
              - "iam:EnableMFADevice"
              - "iam:ResyncMFADevice"
            Resource:
              - "arn:aws:iam::*:mfa/${aws:username}"
              - "arn:aws:iam::*:user/${aws:username}"

  CircleCiPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Policy for cicd accounts
      Path: /
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "ecr:*"
            Resource: "*"

  DeveloperGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: tfn-developers
      Policies:
        - PolicyName: allow-developer-access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "sts:AssumeRole"
                Resource:
                  - !Sub arn:aws:iam::${TestAccountId}:role/tfn-admin-test-eu-west-2
                  - !Sub arn:aws:iam::${PreProdAccountId}:role/tfn-admin-preprod-eu-west-2
                  - !Sub arn:aws:iam::${ProdAccountId}:role/tfn-readonly-prod-eu-west-2
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess
        - !Ref ManageOwnUserPolicy

  ServiceAdminGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: tfn-service-admins
      Policies:
        - PolicyName: allow-service-admin-access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "sts:AssumeRole"
                Resource:
                  - !Sub arn:aws:iam::${TestAccountId}:role/tfn-admin-test-eu-west-2
                  - !Sub arn:aws:iam::${PreProdAccountId}:role/tfn-admin-preprod-eu-west-2
                  - !Sub arn:aws:iam::${ProdAccountId}:role/tfn-admin-prod-eu-west-2
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess
        - !Ref ManageOwnUserPolicy

  BillingGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: tfn-billing
      Policies:
        - PolicyName: allow-billing-access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "sts:AssumeRole"
                Resource:
                  - !Sub arn:aws:iam::${TestAccountId}:role/tfn-billing-test-eu-west-2
                  - !Sub arn:aws:iam::${PreProdAccountId}:role/tfn-billing-preprod-eu-west-2
                  - !Sub arn:aws:iam::${ProdAccountId}:role/tfn-billing-prod-eu-west-2
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/job-function/Billing
        - !Ref ManageOwnUserPolicy

  AdminGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: tfn-admins
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  CircleCiGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: fdbt-core-circleci-group
      ManagedPolicyArns:
        - !Ref CircleCiPolicy

  CircleCiUser:
    Type: AWS::IAM::User
    Properties:
      UserName: fdbt-core-circleci-user
      Groups:
        - !Ref CircleCiGroup
