AWSTemplateFormatVersion: "2010-09-09"

Description: "CloudFormation template for S3 resources"

Parameters:
  TestAccountId:
    Type: String
  PreProdAccountId:
    Type: String

Resources:
  SlackAlertsCodeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: tfn-slack-alerts-code
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: false

  SlackAlertsCodeBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref SlackAlertsCodeBucket
      PolicyDocument:
        Statement:
          - Action:
              - "s3:GetObject"
            Effect: "Allow"
            Resource: !Sub arn:aws:s3:::${SlackAlertsCodeBucket}/*
            Principal:
              AWS:
                - !Sub arn:aws:iam::${TestAccountId}:root
                - !Sub arn:aws:iam::${PreProdAccountId}:root

  CognitoCustomTriggersBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: tfn-cognito-custom-triggers
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: false

  CognitoCustomTriggersBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref CognitoCustomTriggersBucket
      PolicyDocument:
        Statement:
          - Action:
              - "s3:GetObject"
            Effect: "Allow"
            Resource: !Sub arn:aws:s3:::${CognitoCustomTriggersBucket}/*
            Principal:
              AWS:
                - !Sub arn:aws:iam::${TestAccountId}:root
                - !Sub arn:aws:iam::${PreProdAccountId}:root
