service: reference-data-service-uploaders

provider:
  name: aws
  runtime: python3.7
  region: eu-west-2
  stage: ${opt:stage, 'test'}
  stackName: ${self:service}-${self:provider.stage}
  timeout: 900
  memorySize: 2048
  vpc:
    securityGroupIds:
      - ??
    subnetIds:
      - 'Fn::ImportValue': '${self:provider.stage}:PrivateSubnetA'
      - 'Fn::ImportValue': '${self:provider.stage}:PrivateSubnetB'
  environment:
    RDS_HOST: ??
  iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "ssm:GetParameter"
        Resource: "*"
      - Effect: "Allow"
        Action:
          - "s3:GetObject"
        Resource: 
          - !Sub arn:aws:s3:::fdbt-csv-reference-data-${self:provider.stage}/*
          - !Sub arn:aws:s3:::fdbt-xml-reference-data-${self:provider.stage}/*

functions:
  CsvUploader:
    handler: handlers/csv-uploader/handler
    events:
      - s3:
          bucket: fdbt-csv-reference-data-${self:provider.stage}
          event: s3:ObjectCreated:*

  XmlUploader:
    handler: handlers/xml-uploader/handler
    events:
      - s3:
          bucket: fdbt-xml-reference-data-${self:provider.stage}
          event: s3:ObjectCreated:*

package:
    exclude:
        - '*'
    include:
        - ./csv-uploader/*
        - ./xml-uploader/*