version: 2.1
orbs:
  semver-orb: tv2norge/semver-orb@0.0.1

jobs:
  checkout-repo:
    docker:
      - image: circleci/node:12
    working_directory: ~/project
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/project
          paths:
            - "*"

  build-and-test-site:
    docker:
      - image: circleci/node:12
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          command: |
            echo "Starting build"
            npm install
            npm run build
            echo "Running tests"
            npm run test
      - persist_to_workspace:
          root: ~/project
          paths:
            - "node_modules"

  deploy-site:
    docker:
      - image: circleci/node:12
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          command: |
            echo "Deploying..."
            sudo npm i -g serverless
            export NODE_ENV='test' && export SLS_DEBUG="*" && sls deploy
            echo "Finished deploy"

workflows:
  version: 2
  build-test-and-deploy-site:
    jobs:
      - checkout-repo:
          context: "tfn-aws"
          filters:
            branches:
              only: develop
      - build-and-test-site:
          requires:
            - checkout-repo
          context: "tfn-aws"
          filters:
            branches:
              only: develop
      - deploy-site:
          requires:
            - build-and-test-site
          context: "tfn-aws"
          filters:
            branches:
              only: develop
