image: node:12

pipelines:
  default:
    - step:
        script:
          - node --version && npm --version
    - step:
        caches:
          - node-modules-site
        script:
          - npm ci
          - CI=true npm test -- --coverage --detectOpenHandles

definitions:
  caches:
    node-modules-site: node_modules
