service: fdbt

provider:
    name: aws
    runtime: nodejs12.x
    region: eu-west-2
    stage: ${opt:stage, 'test'}
    iamRoleStatements:
        - Effect: 'Allow'
          Action:
              - dynamodb:Query
              - dynamodb:GetItem
          Resource:
              - 'Fn::ImportValue': 'reference-data-service:${self:provider.stage}:NaptanTableArn'
              - 'Fn::ImportValue': 'reference-data-service:${self:provider.stage}:NocTableArn'
              - 'Fn::ImportValue': 'reference-data-service:${self:provider.stage}:ServicesTableArn'
              - 'Fn::ImportValue': 'reference-data-service:${self:provider.stage}:TndsTableArn'
    environment:
        NAPTAN_TABLE_NAME: ${self:provider.stage}-Stops
        NOC_TABLE_NAME: ${self:provider.stage}-Operators
        SERVICES_TABLE_NAME: ${self:provider.stage}-Services
        TNDS_TABLE_NAME: ${self:provider.stage}-TNDS
        AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'

plugins:
    - serverless-nextjs-plugin
    - serverless-domain-manager
    - serverless-offline

custom:
    serverless-nextjs:
        nextConfigDir: './'
        cloudFront: ${file(./serverless.${self:provider.stage}.yml):custom.enableCloudfront}
    customDomain: ${file(./serverless.${self:provider.stage}.yml):custom.customDomain}

resources:
    Resources:
        UnvalidatedUserData:
            Type: AWS::S3::Bucket
            Properties:
                BucketName: fdbt-raw-user-data-${self:provider.stage}
                LifecycleConfiguration:
                    Rules:
                        - Id: ExpiryRule
                          ExpirationInDays: 30
                          Status: Enabled

    Outputs:
        UnvalidatedUserDataBucketName:
            Description: The name of the S3 bucket for Unvalidated User Data
            Value: !Ref UnvalidatedUserData
            Export:
                Name: ${self:service}:${self:provider.stage}:UnvalidatedUserDataBucketName
        UnvalidatedUserDataBucketArn:
            Description: The Arn of the S3 bucket for Unvalidated User Data
            Value: !GetAtt UnvalidatedUserData.Arn
            Export:
                Name: ${self:service}:${self:provider.stage}:UnvalidatedUserDataBucketArn
