service: fdbt

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-2
  stage: ${opt:stage, 'test'}

plugins:
  - serverless-nextjs-plugin
  - serverless-domain-manager
  - serverless-offline

custom:
  serverless-nextjs:
    nextConfigDir: "./"
  customDomain: ${file(./serverless.${self:provider.stage}.yml):custom.customDomain}

functions:
  index:
    handler: handler.hello
    events:
      - http: ANY /

package:
  exclude:
    - ./**