service: fdbt

provider:
    name: aws
    runtime: nodejs12.x
    region: eu-west-2
    stage: ${opt:stage, 'test'}
    iamRoleStatements:
        - Effect: 'Allow'
          Action:
              - dynamodb:Query
              - dynamodb:GetItem
          Resource:
              - 'Fn::ImportValue': 'reference-data-service:${self:provider.stage}:NaptanTableArn'
              - 'Fn::ImportValue': 'reference-data-service:${self:provider.stage}:NocTableArn'
              - 'Fn::ImportValue': 'reference-data-service:${self:provider.stage}:ServicesTableArn'
              - 'Fn::ImportValue': 'reference-data-service:${self:provider.stage}:TndsTableArn'
    environment:
        NAPTAN_TABLE_NAME: ${self:provider.stage}-Stops
        NOC_TABLE_NAME: ${self:provider.stage}-Operators
        SERVICES_TABLE_NAME: ${self:provider.stage}-Services
        TNDS_TABLE_NAME: ${self:provider.stage}-TNDS
        AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'

plugins:
    - serverless-nextjs-plugin
    - serverless-domain-manager
    - serverless-offline

custom:
    serverless-nextjs:
        nextConfigDir: './'
    customDomain: ${file(./serverless.${self:provider.stage}.yml):custom.customDomain}

package:
    exclude:
        - ./**
