image: node:12

pipelines:
  default:
    - step:
        script:
          - node --version && npm --version
    - step:
        caches:
          - node-modules-netex-output-resources
        script:
          - npm ci
          - CI=true npm test -- --coverage --detectOpenHandles

definitions:
    caches:
        node-modules-netex-output-resources: node_modules
