image: node:12

pipelines:
  default:
    - step:
        script:
          - node --version && npm --version
    - step:
        caches:
          - node-modules-reference-data-resources
        script:
          - npm --prefix src/uploaders ci
          - npm --prefix src/uploaders run test:ci -- --coverage --detectOpenHandles

definitions:
  caches:
    node-modules-reference-data-resources: node-modules
