# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs: 
  #Steps for build-data-aggregator
  build-data-aggregator:
    filters:
      branches: #Choose which branch you want to trigger the build
        only: feature/TFN-84_setup_circleci

    docker:
      - image: circleci/node:latest

    steps:
      - checkout

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            pwd
            ls -la
            cd data-aggregator
            sudo npm install

      - run:
          name: Run tests
          command: |
            pwd
            ls -la
            cd data-aggregator
            npm run test

      - run:
          name: Deploy application to tfn-test on aws
          command: |
            echo $AWS_ACCESS_KEY_ID
            cd data-aggregator
            export SLS_DEBUG="*" && sls deploy --aws-profile tfn-test

workflows:
  version: 2
  build-and-test-deliverable-one-lambdas:
    jobs:
      - build-data-aggregator
      # - build-netex-convertor
      # - build-ref-data-uploader
      # - build-odh-uploader
      