# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  "build-data-aggregator":
    branches:
      only: feature/TFN-84_setup_circleci

    docker:
      - image: circleci/node:latest

    steps:
      - checkout

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            pwd
            ls -la
            cd data-aggregator
            sudo npm install

      - run:
          name: Run tests
          command: |
            pwd
            ls -la
            cd data-aggregator
            npm run test

      - run:
          name: Deploy application to tfn-test on aws
          command: |
            pwd
            ls -la
            cd data-aggregator
            export SLS_DEBUG="*" && sls deploy --aws-profile tfn-test

      # Steps for netex-convertor
  "build-netex-convertor":
    branches:
      only: feature/TFN-84_setup_circleci

    docker:
      - image: circleci/node:latest

    steps:
      - checkout

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            cd netex-convertor
            sudo npm install

      - run:
          name: Run tests
          command: |
            pwd
            ls -la
            cd netex-convertor
            npm run test

      - run:
          name: Deploy application to tfn-test on aws
          command: |
            pwd
            ls -la
            cd netex-convertor
            export SLS_DEBUG="*" && sls deploy --aws-profile tfn-test

      # Steps for ref-data-uploader
  "build-ref-data-uploader":
    branches:
      only: feature/TFN-84_setup_circleci

    docker:
      - image: circleci/node:latest

    steps:
      - checkout

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            cd ref-data-uploader
            sudo npm install

      - run:
          name: Run tests
          command: |
            pwd
            ls -la
            cd ref-data-uploader
            npm run test

      - run:
          name: Deploy application to tfn-test on aws
          command: |
            pwd
            ls -la
            cd ref-data-uploader
            export SLS_DEBUG="*" && sls deploy --aws-profile tfn-test

  "build-odh-uploader":
    branches:
      only: feature/TFN-84_setup_circleci

    docker:
      - image: circleci/node:latest

    steps:
      - checkout

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            cd odh-uploader
            sudo npm install

      - run:
          name: Run tests
          command: |
            pwd
            ls -la
            cd odh-uploader
            npm run test

      - run:
          name: Deploy application to tfn-test on aws
          command: |
            pwd
            ls -la
            cd odh-uploader
            export SLS_DEBUG="*" && sls deploy --aws-profile tfn-test

workflows:
  version: 2
  build-and-test-deliverable-one-lambdas:
    jobs:
      - "build-data-aggregator"
      - "build-netex-convertor"
      - "build-ref-data-uploader"
      - "build-odh-uploader"