on:
  push:
    branches:
    - '**'
    - '!develop'
    - '!master'
    paths:
    - repos/exporter/**
  workflow_dispatch:

name: 'exporter'

defaults:
  run:
    working-directory: ./repos/exporter

jobs:

  exporter_to_deploy:
    name: 'exporter'
    runs-on: ubuntu-latest
    env:
      WORKSPACE: preprod
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    
    - name: build
      run: |
        echo "Starting build"
        npm ci
        echo " ci finished"
        npm install -D @types/aws-lambda esbuild
        npm run build-atco-${{ env.WORKSPACE }}
        npm run build-handler-${{ env.WORKSPACE }}
        npm run build-zipper-${{ env.WORKSPACE }}
        npm run build-bastion-${{ env.WORKSPACE }}
        npm run build-table-${{ env.WORKSPACE }}

    - name: test
      run: |
        echo "Running tests"
        npm run test:ci

    - name: lint
      run: |
        echo "Linting"
        npm run lint
