on:
  push:
    branches:
    - 'master'
    paths:
    - repos/exporter/**
  workflow_dispatch:

name: 'exporter_preprod'

defaults:
  run:
    working-directory: ./repos/exporter

jobs:

  exporter_to_deploy_preprod:
    name: 'exporter_preprod'
    runs-on: ubuntu-latest
    env:
      WORKSPACE: preprod
    environment:
      name: preprod
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    
    - name: build
      run: |
        echo "Starting build"
        npm ci
        echo " ci finished"
        npm install -D @types/aws-lambda esbuild
        npm run build-atco-${{ env.WORKSPACE }}
        npm run build-handler-${{ env.WORKSPACE }}
        npm run build-zipper-${{ env.WORKSPACE }}
        npm run build-bastion-${{ env.WORKSPACE }}
        npm run build-table-${{ env.WORKSPACE }}

    - name: test
      run: |
        echo "Running tests"
        npm run test:ci

    - name: lint
      run: |
        echo "Linting"
        npm run lint

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    - name: Update atco code checker
      uses: "./.github/workflows/templates/update_lambda"
      with:
        repo: exporter
        lambda: atco-code-checker
        environment: ${{ env.WORKSPACE }}

    - name: Update exporter lambda
      uses: "./.github/workflows/templates/update_lambda"
      with:
        repo: exporter
        lambda: exporter
        environment: ${{ env.WORKSPACE }}

    - name: Update zipper lambda
      uses: "./.github/workflows/templates/update_lambda"
      with:
        repo: exporter
        lambda: zipper
        environment: ${{ env.WORKSPACE }}

    - name: Update bastion terminator lambda
      uses: "./.github/workflows/templates/update_lambda"
      with:
        repo: exporter
        lambda: bastion-terminator
        environment: ${{ env.WORKSPACE }}

    - name: Update table rename lambda
      uses: "./.github/workflows/templates/update_lambda"
      with:
        repo: exporter
        lambda: table-rename
        environment: ${{ env.WORKSPACE }}
