on:
  push:
    branches:
    - '**'
    paths:
    - repos/exporter/*
  workflow_dispatch:

name: 'exporter'

defaults:
  run:
    working-directory: ./repos/exporter

jobs:

  exporter_to_deploy:
    name: 'exporter'
    runs-on: ubuntu-latest
    env:
      WORKSPACE: none
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set variables
      id: setvars
      run: |
        if [[ "${{github.ref}}" == "refs/heads/develop" ]]; then
          echo "WORKSPACE=test" >> "$GITHUB_ENV"
        fi

        if [[ "${{github.ref}}" == "refs/heads/master" ]]; then
          echo "WORKSPACE=preprod" >> "$GITHUB_ENV"
        fi

    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: 12.x
    
    - name: build
      run: |
        echo "Starting build"
        npm ci
        echo " ci finished"
        npm run build

    - name: test
      run: |
        echo "Running tests"
        npm run test:ci

    - name: lint
      run: |
        echo "Linting"
        npm run lint
    
    - name: deploy-exporter
      if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop' }}
      run: |
        echo "Deploying..."
        export STAGE=${{ env.WORKSPACE }} && node_modules/.bin/cdk deploy --require-approval never --ci --no-color
        echo "Finished deploy" 
