on:
  push:
    branches:
      - "develop"
    paths:
      - repos/fdbt-emailer/**
  workflow_dispatch:

name: "fdbt-emailer-test"

defaults:
  run:
    working-directory: ./repos/fdbt-emailer

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      WORKSPACE: test
    environment:
      name: test

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test:ci

      - name: Build
        run: npm run build-all-functions-${{ env.WORKSPACE }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Update multi-operator-action-required-emailer lambda
        uses: "./.github/workflows/templates/update_lambda"
        with:
          repo: fdbt-emailer
          lambda: fdbt-multi-operator-emailer
          environment: ${{ env.WORKSPACE }}

      - name: Update multi-operator-product-complete-emailer lambda
        uses: "./.github/workflows/templates/update_lambda"
        with:
          repo: fdbt-emailer
          lambda: fdbt-multi-operator-product-complete-emailer
          environment: ${{ env.WORKSPACE }}
