on:
  push:
    branches:
    - '**'
    - '!develop'
    - '!master'
    paths:
    - repos/fdbt-site/**
  workflow_dispatch:

name: 'fdbt-site'

defaults:
  run:
    working-directory: ./repos/fdbt-site
    

jobs:

  fdbt-site:
    name: 'fdbt-site'
    runs-on: ubuntu-latest
    environment:
      name: test
    env:
      WORKSPACE: none
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    - name: run-ui-tests
      env:
        CYPRESS_BASE_URL: ${{ secrets.CYPRESS_BASE_URL }}
        WAF_IPSET_ID: ${{ secrets.WAF_IPSET_ID }}
        WAF_IPSET_NAME: ${{ secrets.WAF_IPSET_NAME }}
      run: |
        cd cypress_tests
        cat cypress.config.ts | sed -e "s/baseUrl: '[^'].*'/baseUrl: '${CYPRESS_BASE_URL}'/g" >> cypress.config.ts2 && mv cypress.config.ts2 cypress.config.ts
        cd ..
        bash run_cypress_tests.sh
    
    - name: build
      run: |
        echo "Starting build"
        npm ci
        echo " ci finished"
        npm run build

    - name: test
      run: |
        echo "Running tests"
        npm run test:ci

    - name: lint
      run: |
        echo "Linting"
        npm run lint

    - name: compile-typescript
      run: |
        echo "Compiling typescript for site"
        ./node_modules/.bin/tsc && ./node_modules/.bin/tsc --project tsconfig.server.json
