on:
  push:
    tags:
    - 'v*'
    paths:
    - repos/fdbt-reference-data-service/**
  workflow_dispatch:

name: 'fdbt-reference-data-service_prod'

defaults:
  run:
    working-directory: ./repos/fdbt-reference-data-service

jobs:

  fdbt-reference-data-service_deploy_to_prod:
    name: 'fdbt-reference-data-service_to_prod'
    runs-on: ubuntu-latest
    env:
      WORKSPACE: prod
    environment:
      name: prod
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.12
      
    - name: audit-reference-data-retrievers
      run: |
        pip install safety
        cd src/retrievers
        safety check -r requirements.txt

    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: 14.x

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    - name: audit-reference-data-uploaders
      run: |
        pip install safety
        cd src/uploaders
        safety check -r requirements.txt
        safety check -r requirements.test.txt
    
    - name: test-reference-data-uploaders
      run: |
        cd src/uploaders
        pip install -r requirements.test.txt
        echo "Running tests..."
        python3 -m pytest tests/
    
    - name: Zipping code for deploy-reference-data-uploader-TxcUnzipper
      run: |
        echo "Zipping..."
        cd src/retrievers
        pip install --target=/home/runner/work/create-data/create-data/repos/fdbt-reference-data-service/src/retrievers -r requirements.txt
        pwd
        ls
        zip -r reference-data-service-retrievers-prod-TxcUnzipper.zip . -x /package.json -x /serverless.yml -x /package-lock.json  
        zip -sf reference-data-service-retrievers-prod-TxcUnzipper.zip
        ls

    - name: reference-data-service-retrievers-prod-TxcUnzipper
      run: |
        echo "Updating..."
        cd src/retrievers        
        aws lambda update-function-code --function-name reference-data-service-retrievers-prod-TxcUnzipper --zip-file fileb://reference-data-service-retrievers-prod-TxcUnzipper.zip
        rm -f reference-data-service-retrievers-prod-TxcUnzipper.zip

    - name: Zipping code for deploy-reference-data-uploader-NocRetriever
      run: |
        echo "Zipping..."
        cd src/retrievers
        pip install --target=/home/runner/work/create-data/create-data/repos/fdbt-reference-data-service/src/retrievers -r requirements.txt
        pwd
        ls
        zip -r reference-data-service-retrievers-prod-NocRetriever.zip . -x /package.json -x /serverless.yml -x /package-lock.json  
        zip -sf reference-data-service-retrievers-prod-NocRetriever.zip
        ls

    - name: reference-data-service-retrievers-prod-NocRetriever
      run: |
        echo "Updating..."
        cd src/retrievers        
        aws lambda update-function-code --function-name reference-data-service-retrievers-prod-NocRetriever --zip-file fileb://reference-data-service-retrievers-prod-NocRetriever.zip
        rm -f reference-data-service-retrievers-prod-NocRetriever.zip


    - name: Zipping code for deploy-reference-data-uploader-TxcRetrieverTnds
      run: |
        echo "Zipping..."
        cd src/retrievers
        pip install --target=/home/runner/work/create-data/create-data/repos/fdbt-reference-data-service/src/retrievers -r requirements.txt
        pwd
        ls
        zip -r reference-data-service-retrievers-prod-TxcRetrieverTnds.zip . -x /package.json -x /serverless.yml -x /package-lock.json  
        zip -sf reference-data-service-retrievers-prod-TxcRetrieverTnds.zip
        ls

    - name: reference-data-service-retrievers-prod-TxcRetrieverTnds
      run: |
        echo "Updating..."
        cd src/retrievers        
        aws lambda update-function-code --function-name reference-data-service-retrievers-prod-TxcRetrieverTnds --zip-file fileb://reference-data-service-retrievers-prod-TxcRetrieverTnds.zip
        rm -f reference-data-service-retrievers-prod-TxcRetrieverTnds.zip

    - name: Zipping code for deploy-reference-data-uploader-NaptanRetriever
      run: |
        echo "Zipping..."
        cd src/retrievers
        pip install --target=/home/runner/work/create-data/create-data/repos/fdbt-reference-data-service/src/retrievers -r requirements.txt
        pwd
        ls
        zip -r reference-data-service-retrievers-prod-NaptanRetriever.zip . -x /package.json -x /serverless.yml -x /package-lock.json  
        zip -sf reference-data-service-retrievers-prod-NaptanRetriever.zip
        ls

    - name: reference-data-service-retrievers-prod-NaptanRetriever
      run: |
        echo "Updating..."
        cd src/retrievers        
        aws lambda update-function-code --function-name reference-data-service-retrievers-prod-NaptanRetriever --zip-file fileb://reference-data-service-retrievers-prod-NaptanRetriever.zip
        rm -f  reference-data-service-retrievers-prod-NaptanRetriever.zip

    - name: Zipping code for deploy-reference-data-uploader-TxcRetrieverBods
      run: |
        echo "Zipping..."
        cd src/retrievers
        pip install --target=/home/runner/work/create-data/create-data/repos/fdbt-reference-data-service/src/retrievers -r requirements.txt
        pwd
        ls
        zip -r reference-data-service-retrievers-prod-TxcRetrieverBods.zip . -x /package.json -x /serverless.yml -x /package-lock.json  
        zip -sf reference-data-service-retrievers-prod-TxcRetrieverBods.zip
        ls

    - name: reference-data-service-retrievers-prod-TxcRetrieverBods
      run: |
        echo "Updating..."
        cd src/retrievers        
        aws lambda update-function-code --function-name reference-data-service-retrievers-prod-TxcRetrieverBods --zip-file fileb://reference-data-service-retrievers-prod-TxcRetrieverBods.zip
        rm -f  reference-data-service-retrievers-prod-TxcRetrieverBods.zip           


    - name: Zipping code for deploy-reference-uploaders-prod-CsvUploader
      run: |
        echo "Zipping..."
        cd src/uploaders
        pip install --target=/home/runner/work/create-data/create-data/repos/fdbt-reference-data-service/src/uploaders -r requirements.txt
        pwd
        ls
        zip -r reference-data-service-uploaders-prod-CsvUploader.zip . -x /package.json -x /serverless.yml -x /package-lock.json  
        zip -sf reference-data-service-uploaders-prod-CsvUploader.zip
        ls -l

    - name: reference-data-service-uploaders-prod-CsvUploader
      run: |
        echo "Updating..."
        cd src/uploaders        
        aws lambda update-function-code --function-name reference-data-service-uploaders-prod-CsvUploader --zip-file fileb://reference-data-service-uploaders-prod-CsvUploader.zip
        rm -f reference-data-service-uploaders-prod-CsvUploader.zip

    - name: Zipping code for deploy-reference-uploaders-prod-CsvUploader
      run: |
        echo "Zipping..."
        cd src/uploaders
        pip install --target=/home/runner/work/create-data/create-data/repos/fdbt-reference-data-service/src/uploaders -r requirements.txt
        pwd
        ls
        zip -r reference-data-service-uploaders-prod-TxcUploader.zip . -x /package.json -x /serverless.yml -x /package-lock.json  
        zip -sf reference-data-service-uploaders-prod-TxcUploader.zip
        ls -l

    - name: reference-data-service-uploaders-prod-TxcUploader
      run: |
        echo "Updating..."
        cd src/uploaders        
        aws lambda update-function-code --function-name reference-data-service-uploaders-prod-TxcUploader --zip-file fileb://reference-data-service-uploaders-prod-TxcUploader.zip
        rm -f reference-data-service-uploaders-prod-TxcUploader.zip
    
    

    


    
    