on:
  push:
    branches:
      - "master"
    paths:
      - repos/fdbt-multi-operator-emailer/**
  workflow_dispatch:

name: "fdbt-multi-operator-emailer-preprod"

defaults:
  run:
    working-directory: ./repos/fdbt-multi-operator-emailer

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      WORKSPACE: preprod
    environment:
      name: preprod

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test:ci

      - name: Build
        run: npm run build-${{ env.WORKSPACE }}

      - name: Archive build
        run: zip package.zip *
        working-directory: ./dist/multi-operator-emailer-${{ env.WORKSPACE }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Deploy Lambda
        run: aws lambda update-function-code --function-name fdbt-multi-operator-emailer-${{ env.WORKSPACE }} --zip-file fileb://dist/multi-operator-emailer-${{ env.WORKSPACE }}/package.zip
