on:
  push:
    branches:
    - '**'
    - '!develop'
    - '!master'
    paths:
    - repos/fdbt-site/**
  workflow_dispatch:

name: 'fdbt-site'

defaults:
  run:
    working-directory: ./repos/fdbt-site
    

jobs:

  fdbt-site:
    name: 'fdbt-site'
    runs-on: ubuntu-latest
    env:
      WORKSPACE: none
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    
    - name: build
      run: |
        echo "Starting build"
        npm ci
        echo " ci finished"
        npm run build

    - name: test
      run: |
        echo "Running tests"
        npm run test:ci -- -u

    - name: lint
      run: |
        echo "Linting"
        npm run lint

    - name: compile-typescript
      run: |
        echo "Compiling typescript for site"
        ./node_modules/.bin/tsc && ./node_modules/.bin/tsc --project tsconfig.server.json
