on:
  workflow_run:
    workflows: ["fdbt-site_test"]
    # branches: ['develop']
    types:
      - completed

name: 'fdbt-site_test_ui_tests'

jobs:

  fdbt-site_test_ui_tests:
    name: 'fdbt-site_test_ui_tests'
    runs-on: ubuntu-latest
    environment:
      name: test
    env:
      ECS_SERVICE: ${{ secrets.ECS_SERVICE }}                 # set this to your Amazon ECS service name
      ECS_CLUSTER: ${{ secrets.ECS_CLUSTER }}                 # set this to your Amazon ECS cluster name
      ECS_TASK_DEFINITION: ${{ secrets.ECS_TASK_DEFINITION }} # set this to the path to your Amazon ECS task definition
      CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
      WAF_IPSET_ID: ${{ secrets.WAF_IPSET_ID }}
      WAF_IPSET_NAME: ${{ secrets.WAF_IPSET_NAME }}


    steps:

    - name: Sleep for 10 mins
      run: sleep 10m
      shell: bash

    - name: run-ui-tests
      env:
        CYPRESS_BASE_URL: ${{ secrets.CYPRESS_BASE_URL }}
      run: |
        cd cypress_tests
        cat cypress.config.ts | sed -e "s/baseUrl: '[^'].*'/baseUrl: '${CYPRESS_BASE_URL}'/g" >> cypress.config.ts2 && mv cypress.config.ts2 cypress.config.ts
        cd ..
        bash run_tests_in_browserstack.sh

