on:
  push:
    tags:
    - 'v*'
    paths:
    - repos/fdbt-reference-data-service/**
  workflow_dispatch:

name: 'fdbt-reference-data-service_prod'

defaults:
  run:
    working-directory: ./repos/fdbt-reference-data-service

jobs:

  fdbt-reference-data-service_deploy_to_preprod:
    name: 'fdbt-reference-data-service_to_preprod'
    runs-on: ubuntu-latest
    env:
      WORKSPACE: preprod
    environment:
      name: preprod
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
      
    - name: audit-reference-data-retrievers
      run: |
        pip install safety
        cd src/retrievers
        safety check -r requirements.txt

    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: 14.x

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    # - name: deploy-reference-data-retrievers
    #   run: |
    #     echo "Deploying..."
    #     curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
    #     sudo apt-get install -y nodejs
    #     cd src/retrievers
    #     npm ci
    #     npm run deploy:${{ env.WORKSPACE }}
    #     echo "Finished deploy"

    - name: audit-reference-data-uploaders
      run: |
        pip install safety
        cd src/uploaders
        safety check -r requirements.txt
        safety check -r requirements.test.txt
    
    - name: test-reference-data-uploaders
      run: |
        cd src/uploaders
        pip install -r requirements.test.txt
        echo "Running tests..."
        python3 -m pytest tests/

    # - name: deploy-reference-data-uploaders-to
    #   run: |
    #     echo "Deploying..."
    #     curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
    #     sudo apt-get install -y nodejs
    #     cd src/uploaders
    #     npm ci
    #     npm run deploy:${{ env.WORKSPACE }}
    #     echo "Finished deploy"

    
    - name: Zipping code for deploy-reference-data-uploader-TxcUnzipper
      run: |
        echo "Zipping..."
        cd src/retrievers
        pip install --target=/home/runner/work/ie-igh-sandbox/ie-igh-sandbox/repos/fdbt-reference-data-service/src/retrievers -r requirements.txt
        pwd
        ls
        zip -r reference-data-service-retrievers-preprod-TxcUnzipper.zip . -x /package.json -x /serverless.yml -x /package-lock.json  
        zip -sf reference-data-service-retrievers-preprod-TxcUnzipper.zip
        ls

    - name: reference-data-service-retrievers-preprod-TxcUnzipper
      run: |
        echo "Updating..."
        cd src/retrievers        
        aws lambda update-function-code --function-name reference-data-service-retrievers-preprod-TxcUnzipper --zip-file fileb://reference-data-service-retrievers-preprod-TxcUnzipper.zip
        rm -f reference-data-service-retrievers-preprod-TxcUnzipper.zip

    - name: Zipping code for deploy-reference-data-uploader-NocRetriever
      run: |
        echo "Zipping..."
        cd src/retrievers
        pip install --target=/home/runner/work/ie-igh-sandbox/ie-igh-sandbox/repos/fdbt-reference-data-service/src/retrievers -r requirements.txt
        pwd
        ls
        zip -r reference-data-service-retrievers-preprod-NocRetriever.zip . -x /package.json -x /serverless.yml -x /package-lock.json  
        zip -sf reference-data-service-retrievers-preprod-NocRetriever.zip
        ls

    - name: reference-data-service-retrievers-preprod-NocRetriever
      run: |
        echo "Updating..."
        cd src/retrievers        
        aws lambda update-function-code --function-name reference-data-service-retrievers-preprod-NocRetriever --zip-file fileb://reference-data-service-retrievers-preprod-NocRetriever.zip
        rm -f reference-data-service-retrievers-preprod-NocRetriever.zip


    - name: Zipping code for deploy-reference-data-uploader-TxcRetrieverTnds
      run: |
        echo "Zipping..."
        cd src/retrievers
        pip install --target=/home/runner/work/ie-igh-sandbox/ie-igh-sandbox/repos/fdbt-reference-data-service/src/retrievers -r requirements.txt
        pwd
        ls
        zip -r reference-data-service-retrievers-preprod-TxcRetrieverTnds.zip . -x /package.json -x /serverless.yml -x /package-lock.json  
        zip -sf reference-data-service-retrievers-preprod-TxcRetrieverTnds.zip
        ls

    - name: reference-data-service-retrievers-preprod-TxcRetrieverTnds
      run: |
        echo "Updating..."
        cd src/retrievers        
        aws lambda update-function-code --function-name reference-data-service-retrievers-preprod-TxcRetrieverTnds --zip-file fileb://reference-data-service-retrievers-preprod-TxcRetrieverTnds.zip
        rm -f reference-data-service-retrievers-preprod-TxcRetrieverTnds.zip

    - name: Zipping code for deploy-reference-data-uploader-NaptanRetriever
      run: |
        echo "Zipping..."
        cd src/retrievers
        pip install --target=/home/runner/work/ie-igh-sandbox/ie-igh-sandbox/repos/fdbt-reference-data-service/src/retrievers -r requirements.txt
        pwd
        ls
        zip -r reference-data-service-retrievers-preprod-NaptanRetriever.zip . -x /package.json -x /serverless.yml -x /package-lock.json  
        zip -sf reference-data-service-retrievers-preprod-NaptanRetriever.zip
        ls

    - name: reference-data-service-retrievers-preprod-NaptanRetriever
      run: |
        echo "Updating..."
        cd src/retrievers        
        aws lambda update-function-code --function-name reference-data-service-retrievers-preprod-NaptanRetriever --zip-file fileb://reference-data-service-retrievers-preprod-NaptanRetriever.zip
        rm -f  reference-data-service-retrievers-preprod-NaptanRetriever.zip

    - name: Zipping code for deploy-reference-data-uploader-TxcRetrieverBods
      run: |
        echo "Zipping..."
        cd src/retrievers
        pip install --target=/home/runner/work/ie-igh-sandbox/ie-igh-sandbox/repos/fdbt-reference-data-service/src/retrievers -r requirements.txt
        pwd
        ls
        zip -r reference-data-service-retrievers-preprod-TxcRetrieverBods.zip . -x /package.json -x /serverless.yml -x /package-lock.json  
        zip -sf reference-data-service-retrievers-preprod-TxcRetrieverBods.zip
        ls

    - name: reference-data-service-retrievers-preprod-TxcRetrieverBods
      run: |
        echo "Updating..."
        cd src/retrievers        
        aws lambda update-function-code --function-name reference-data-service-retrievers-preprod-TxcRetrieverBods --zip-file fileb://reference-data-service-retrievers-preprod-TxcRetrieverBods.zip
        rm -f  reference-data-service-retrievers-preprod-TxcRetrieverBods.zip           


    - name: Zipping code for deploy-reference-uploaders-preprod-CsvUploader
      run: |
        echo "Zipping..."
        cd src/uploaders
        pip install --target=/home/runner/work/ie-igh-sandbox/ie-igh-sandbox/repos/fdbt-reference-data-service/src/uploaders -r requirements.txt
        pwd
        ls
        zip -r reference-data-service-uploaders-preprod-CsvUploader.zip . -x /package.json -x /serverless.yml -x /package-lock.json  
        zip -sf reference-data-service-uploaders-preprod-CsvUploader.zip
        ls -l

    - name: reference-data-service-uploaders-preprod-CsvUploader
      run: |
        echo "Updating..."
        cd src/uploaders        
        aws lambda update-function-code --function-name reference-data-service-uploaders-preprod-CsvUploader --zip-file fileb://reference-data-service-uploaders-preprod-CsvUploader.zip
        rm -f reference-data-service-uploaders-preprod-CsvUploader.zip

    - name: Zipping code for deploy-reference-uploaders-preprod-CsvUploader
      run: |
        echo "Zipping..."
        cd src/uploaders
        pip install --target=/home/runner/work/ie-igh-sandbox/ie-igh-sandbox/repos/fdbt-reference-data-service/src/uploaders -r requirements.txt
        pwd
        ls
        zip -r reference-data-service-uploaders-preprod-TxcUploader.zip . -x /package.json -x /serverless.yml -x /package-lock.json  
        zip -sf reference-data-service-uploaders-preprod-TxcUploader.zip
        ls -l

    - name: reference-data-service-uploaders-preprod-TxcUploader
      run: |
        echo "Updating..."
        cd src/uploaders        
        aws lambda update-function-code --function-name reference-data-service-uploaders-preprod-TxcUploader --zip-file fileb://reference-data-service-uploaders-preprod-TxcUploader.zip
        rm -f reference-data-service-uploaders-preprod-TxcUploader.zip
    
    

    


    
    
