on:
  push:
    branches:
    - '**'
    paths:
    - repos/fdbt-netex-output/*
  workflow_dispatch:

name: 'fdbt-netex-output'

defaults:
  run:
    working-directory: ./repos/fdbt-netex-output

jobs:

  fdbt-netex-output:
    name: 'fdbt-netex-output'
    runs-on: ubuntu-latest
    environment:
      name: test
    env:
      WORKSPACE: none
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set variables
      id: setvars
      run: |
        if [[ "${{github.ref}}" == "refs/heads/develop" ]]; then
          echo "WORKSPACE=test" >> "$GITHUB_ENV"
        fi

        if [[ "${{github.ref}}" == "refs/heads/master" ]]; then
          echo "WORKSPACE=preprod" >> "$GITHUB_ENV"
        fi

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
      
    - name: audit-netex-validator
      run: |
        pip install safety
        cd src/netex-validator
        safety check -r requirements.txt
    
    - name: deploy-netex-validator 
      run: |
        echo "Deploying..."
        curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
        sudo apt-get install -y nodejs
        sudo npm i -g serverless@3.22.0
        cd src/netex-validator
        npm ci
        export SLS_DEBUG="*" && sls deploy --stage=${{ env.WORKSPACE }}
        echo "Finished deploy"

    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: 12.x
    
    - name: build
      run: |
        echo "Starting build"
        npm ci
        echo " ci finished"
        npm run build

    - name: test
      run: |
        echo "Running tests"
        npm run test:ci

    - name: lint
      run: |
        echo "Linting"
        npm run lint
    
    - name: deploy-netex-output-resources
      run: |
        echo "Deploying..."
        sudo npm i -g serverless@3.22.0
        export SLS_DEBUG="*" && sls deploy --stage=${{ env.WORKSPACE }}
        echo "Finished deploy"


    
    
